-- ------------------------------------------------------------
-- Copyright 2009-2014 RED.ES - Desarrollado por TIER1
-- 
-- Licencia con arreglo a la EUPL, versión 1.1 o -en cuanto 
-- sean aprobadas por la comisión Europea- versiones 
-- posteriores de la EUPL (la "Licencia").
-- Solo podrá usarse esta obra si se respeta la Licencia.
-- 
-- http://ec.europa.eu/idabc/eupl.html
-- 
-- Salvo cuando lo exija la legislación aplicable o se acuerde
-- por escrito, el programa distribuido con arreglo a la
-- Licencia se distribuye "TAL CUAL",
-- SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, 
-- ni expresas ni implícitas.
-- Véase la Licencia en el idioma concreto que rige
-- los permisos y limitaciones que establece la Licencia.
-- ------------------------------------------------------------

CREATE OR REPLACE VIEW CONFIG_ACCIONES_PERMISOS (
   ID_ACCION,
   ID_OPERACION,
   DESOPERACION,
   ID_USUARIO,
   ID_PERFIL,
   ACCESO,
   ORDEN,
   DESUSUARIO,
   DESPERFIL )
AS
SELECT PERMISO.ID_ACCION, PERMISO.ID_OPERACION, OPERACION.DESOPERACION,
       PERMISO.ID_USUARIO, PERMISO.ID_PERFIL, PERMISO.ACCESO, OPERACION.ORDEN,
       USUARIOS.DESUSUARIO, PERFILES.DESPERFIL
  FROM CONFIG_ACCIONES_PERMISOS_TBL PERMISO
  INNER JOIN CONFIG_ACCIONES_OPERACIONE_TBL OPERACION
      ON (OPERACION.ID_ACCION = PERMISO.ID_ACCION AND OPERACION.ID_OPERACION = PERMISO.ID_OPERACION)
  LEFT JOIN CONFIG_USUARIOS_TBL USUARIOS
      ON (USUARIOS.ID_USUARIO = PERMISO.ID_USUARIO)
  LEFT JOIN CONFIG_PERFILES_TBL PERFILES
      ON (PERFILES.ID_PERFIL = PERMISO.ID_PERFIL)
;
CREATE OR REPLACE VIEW CONFIG_APLICACIONES_WEB (
   CODAPLICACION,
   DESAPLICACION )
AS
SELECT DISTINCT MENU.APLICACION AS CODAPLICACION,
                MENU.APLICACION AS DESAPLICACION
  FROM CONFIG_MENU_TBL MENU,
       CONFIG_ACCIONES_TBL ACCIONES
 WHERE (ACCIONES.ID_ACCION = MENU.ID_ACCION AND ACCIONES.TIPO_ACCION = 'URL')
;
CREATE OR REPLACE VIEW CONFIG_IMP_GRUPOS (
   ID_GRUPO_IMPUESTOS,
   VIGENCIA_DESDE )
AS
SELECT ID_GRUPO_IMPUESTOS,
       CAST(CAST(VIGENCIA_DESDE AS DATE) AS CHAR(10)) AS VIGENCIA_DESDE
    FROM CONFIG_IMP_GRUPOS_TBL
;
CREATE OR REPLACE VIEW CONFIG_IMP_PORCENTAJES (
   ID_GRUPO_IMPUESTOS,
   VIGENCIA_DESDE,
   ID_TRAT_IMPUESTOS,
   CODTRATIMP,
   DESTRATIMP,
   APLICA_RECARGO,
   CODIMP,
   DESIMP,
   PORCENTAJE,
   PORCENTAJE_RECARGO )
AS
SELECT PORCENTAJES.ID_GRUPO_IMPUESTOS, GRUPOS.VIGENCIA_DESDE, PORCENTAJES.ID_TRAT_IMPUESTOS, TRAT.CODTRATIMP,
    TRAT.DESTRATIMP, TRAT.APLICA_RECARGO, PORCENTAJES.CODIMP, TIPOS.DESIMP, PORCENTAJES.PORCENTAJE,
    PORCENTAJES.PORCENTAJE_RECARGO
FROM CONFIG_IMP_PORCENTAJES_TBL PORCENTAJES
    LEFT JOIN CONFIG_IMP_GRUPOS_TBL GRUPOS ON (PORCENTAJES.ID_GRUPO_IMPUESTOS = GRUPOS.ID_GRUPO_IMPUESTOS)
    LEFT JOIN CONFIG_IMP_TRATAMIENTO_TBL TRAT ON (PORCENTAJES.ID_TRAT_IMPUESTOS = TRAT.ID_TRAT_IMPUESTOS)
    LEFT JOIN CONFIG_IMP_TIPOS_TBL TIPOS ON (PORCENTAJES.CODIMP = TIPOS.CODIMP)
;
CREATE OR REPLACE VIEW CONFIG_MENU (
   APLICACION,
   ORDEN,
   OPCION,
   ID_ACCION,
   TECLA_RAPIDA,
   TIPO_ACCION,
   EJECUCION,
   PARAMETROS,
   DESCRIPCION,
   TITULO,
   ICONO )
AS
SELECT
   MENU.APLICACION, MENU.ORDEN, MENU.OPCION, MENU.ID_ACCION, MENU.TECLA_RAPIDA,
   ACCION.TIPO_ACCION, ACCION.EJECUCION, ACCION.PARAMETROS, ACCION.DESCRIPCION,
   ACCION.TITULO, ACCION.ICONO
FROM
   CONFIG_MENU_TBL MENU
   LEFT JOIN CONFIG_ACCIONES_TBL ACCION ON (ACCION.ID_ACCION = MENU.ID_ACCION)
;
CREATE OR REPLACE VIEW CONFIG_USUARIOS_PERFILES (
   ID_USUARIO,
   ID_PERFIL,
   DESPERFIL )
AS
SELECT USU.ID_USUARIO, USU.ID_PERFIL, PERF.DESPERFIL
		FROM CONFIG_PERFILES_TBL PERF
						 LEFT JOIN CONFIG_USUARIOS_PERFILES_TBL USU ON (PERF.ID_PERFIL = USU.ID_PERFIL)
;
CREATE OR REPLACE VIEW CONFIG_VARIABLES (
   ID_VARIABLE,
   DESCRIPCION,
   VALOR_DEFECTO,
   VALOR,
   PESO )
AS
SELECT DEFI.ID_VARIABLE, DEFI.DESCRIPCION, DEFI.VALOR_DEFECTO, VARI.VALOR, VARI.PESO
  FROM CONFIG_VARIABLES_DEF_TBL DEFI
        LEFT JOIN CONFIG_VARIABLES_TBL VARI ON (DEFI.ID_VARIABLE = VARI.ID_VARIABLE)
;
CREATE OR REPLACE VIEW D_ALMACENES (
   CODALM,
   DESALM,
   DOMICILIO,
   POBLACION,
   PROVINCIA,
   CP,
   TELEFONO1,
   TELEFONO2,
   FAX,
   PERSONA_CONTACTO,
   CODEMP,
   CODCLI,
   DESCLI,
   ACTIVO )
AS
SELECT ALMACEN.CODALM, ALMACEN.DESALM, ALMACEN.DOMICILIO, ALMACEN.POBLACION,
        ALMACEN.PROVINCIA, ALMACEN.CP, ALMACEN.TELEFONO1, ALMACEN.TELEFONO2,
        ALMACEN.FAX, ALMACEN.PERSONA_CONTACTO, ALMACEN.CODEMP, ALMACEN.CODCLI,
        CLIENTE.DESCLI, ALMACEN.ACTIVO
FROM D_ALMACENES_TBL ALMACEN
							INNER JOIN D_CLIENTES_TBL CLIENTE ON (ALMACEN.CODCLI = CLIENTE.CODCLI)
;
CREATE OR REPLACE VIEW D_ALMACENES_ARTICULOS (
   CODALM,
   CODART,
   DESALM,
   DESGLOSE1,
   DESGLOSE2,
   STOCK,
   STOCK_UM_ALTERNATIVA,
   STOCK_MINIMO,
   STOCK_MAXIMO,
   STOCK_PENDIENTE_RECIBIR,
   STOCK_PENDIENTE_SERVIR,
   UBICACION1,
   UBICACION2,
   UBICACION3,
   UBICACION4,
   PMP,
   ACTIVO )
AS
SELECT ARTICULOS.CODALM, ARTICULOS.CODART, ALMACENES.DESALM, ARTICULOS.DESGLOSE1, ARTICULOS.DESGLOSE2, ARTICULOS.STOCK,
        ARTICULOS.STOCK_UM_ALTERNATIVA, ARTICULOS.STOCK_MINIMO, ARTICULOS.STOCK_MAXIMO, ARTICULOS.STOCK_PENDIENTE_RECIBIR,
        ARTICULOS.STOCK_PENDIENTE_SERVIR, ARTICULOS.UBICACION1, ARTICULOS.UBICACION2, ARTICULOS.UBICACION3,
        ARTICULOS.UBICACION4, ARTICULOS.PMP, ARTICULOS.ACTIVO
FROM D_ALMACENES_ARTICULOS_TBL ARTICULOS
        LEFT JOIN D_ALMACENES_TBL ALMACENES ON (ALMACENES.CODALM = ARTICULOS.CODALM)
;
CREATE OR REPLACE VIEW D_ALMACENES_CONCEPTOS (
   CODAPLICACION,
   CODCONALM,
   DESCONALM,
   SIGNO,
   CODALM_ORIGEN,
   DESALM_ORIGEN,
   CODALM_DESTINO,
   DESALM_DESTINO,
   SOLICITUD_ACEPTACION_AUTO,
   SOLICITUD_RECEPCION_AUTO,
   SOLICITUD_GENERAR_FALTAS,
   VISIBLE_TIENDAS,
   ACTIVO )
AS
SELECT CONCEPTO_ALM.CODAPLICACION,
       CONCEPTO_ALM.CODCONALM,
       CONCEPTO_ALM.DESCONALM,
       CONCEPTO_ALM.SIGNO,
	      CONCEPTO_ALM.CODALM_ORIGEN,
	      ALMACENES_ORIGEN.DESALM AS DESALM_ORIGEN,
       CONCEPTO_ALM.CODALM_DESTINO,
	      ALMACENES_DESTINO.DESALM AS DESALM_DESTINO,
       CONCEPTO_ALM.SOLICITUD_ACEPTACION_AUTO,
							CONCEPTO_ALM.SOLICITUD_RECEPCION_AUTO,
       CONCEPTO_ALM.SOLICITUD_GENERAR_FALTAS,
			    CONCEPTO_ALM.VISIBLE_TIENDAS,
       CONCEPTO_ALM.ACTIVO
	 FROM D_ALMACENES_CONCEPTOS_TBL CONCEPTO_ALM
	      LEFT JOIN D_ALMACENES_TBL ALMACENES_ORIGEN ON CONCEPTO_ALM.CODALM_ORIGEN = ALMACENES_ORIGEN.CODALM
	      LEFT JOIN D_ALMACENES_TBL ALMACENES_DESTINO ON CONCEPTO_ALM.CODALM_DESTINO = ALMACENES_DESTINO.CODALM
;
CREATE OR REPLACE VIEW D_ALMACENES_REGULARIZA (
   ID_REGULARIZACION,
   CODART,
   CODALM,
   CODCONALM,
   FECHA,
   CODAPLICACION,
   DESART,
   DESALM,
   DESCONALM,
   DESGLOSE1,
   DESGLOSE2,
   CANTIDAD_MEDIDA,
   UNIDAD_MEDIDA,
   CANTIDAD,
   PRECIO,
   IMPORTE,
   OBSERVACIONES,
   ID_USUARIO )
AS
SELECT REGU.ID_REGULARIZACION, REGU.CODART, REGU.CODALM, REGU.CODCONALM, REGU.FECHA,
        REGU.CODAPLICACION, ART.DESART, ALM.DESALM, CONCEPTO.DESCONALM, REGU.DESGLOSE1, REGU.DESGLOSE2,
        REGU.CANTIDAD_MEDIDA, REGU.UNIDAD_MEDIDA, REGU.CANTIDAD, REGU.PRECIO,
        REGU.IMPORTE, REGU.OBSERVACIONES, REGU.ID_USUARIO
FROM D_ALMACENES_REGULARIZA_TBL REGU
    LEFT JOIN D_ARTICULOS_TBL ART ON (REGU.CODART = ART.CODART)
    LEFT JOIN D_ALMACENES_TBL ALM ON (REGU.CODALM = ALM.CODALM)
    LEFT JOIN D_ALMACENES_CONCEPTOS_TBL CONCEPTO ON (REGU.CODCONALM = CONCEPTO.CODCONALM AND CONCEPTO.CODAPLICACION = 'REGU')
;
CREATE OR REPLACE VIEW D_ALMACENES_USUARIOS (
   ID_USUARIO,
   USUARIO,
   DESUSUARIO,
   CODALM,
   DESALM )
AS
SELECT ALMUSU.ID_USUARIO, USUARIOS.USUARIO, USUARIOS.DESUSUARIO, ALMUSU.CODALM, ALM.DESALM
		FROM D_ALMACENES_TBL ALM
	    LEFT JOIN D_ALMACENES_USUARIOS_TBL ALMUSU ON (ALM.CODALM = ALMUSU.CODALM)
	    LEFT JOIN CONFIG_USUARIOS_TBL USUARIOS ON (ALMUSU.ID_USUARIO = USUARIOS.ID_USUARIO)
;
CREATE OR REPLACE VIEW D_ARTICULOS (
   CODART,
   DESART,
   FORMATO,
   CODFAM,
   DESFAM,
   CODSECCION,
   DESSECCION,
   CODCAT,
   DESCAT,
   CODPRO,
   DESPRO,
   REFERENCIA_PROVEEDOR,
   DTO_PROVEEDOR,
   PMP,
   ACT_AUTOMATICA_COSTO,
   COSTO_ACTUALIZADO,
   CODIMP,
   DESIMP,
   OBSERVACIONES,
   ACTIVO,
   NUMEROS_SERIE,
   DESGLOSE1,
   DESGLOSE2,
   GENERICO,
   ESCAPARATE,
   UNIDAD_MEDIDA_ALTERNATIVA,
   VERSION,
   COD_UM_ETIQUETA,
   DES_UM_ETIQUETA,
   CANTIDAD_UM_ETIQUETA,
   CODFAB,
   DESFAB )
AS
SELECT ARTICULOS.CODART, ARTICULOS.DESART, ARTICULOS.FORMATO, ARTICULOS.CODFAM,
							FAMILIA.DESFAM, ARTICULOS.CODSECCION, SECCION.DESSECCION,
							ARTICULOS.CODCAT, CAT.DESCAT, ARTICULOS.CODPRO, PROV.DESPRO, ARTICULOS.REFERENCIA_PROVEEDOR,
							ARTICULOS.DTO_PROVEEDOR, ARTICULOS.PMP, ARTICULOS.ACT_AUTOMATICA_COSTO,
							ARTICULOS.COSTO_ACTUALIZADO, ARTICULOS.CODIMP, IMP.DESIMP, ARTICULOS.OBSERVACIONES,
							ARTICULOS.ACTIVO, ARTICULOS.NUMEROS_SERIE, ARTICULOS.DESGLOSE1,
       ARTICULOS.DESGLOSE2, ARTICULOS.GENERICO, ARTICULOS.ESCAPARATE,
       ARTICULOS.UNIDAD_MEDIDA_ALTERNATIVA, ARTICULOS.VERSION, ARTICULOS.COD_UM_ETIQUETA,
       UNIDAD.DES_UM_ETIQUETA, ARTICULOS.CANTIDAD_UM_ETIQUETA, ARTICULOS.CODFAB, FABRICANTE.DESPRO AS DESFAB
  FROM D_ARTICULOS_TBL ARTICULOS
  					LEFT JOIN D_UNIDAD_MEDIDA_ETIQUETAS_TBL UNIDAD ON (UNIDAD.COD_UM_ETIQUETA = ARTICULOS.COD_UM_ETIQUETA)
  					LEFT JOIN D_FAMILIAS_TBL FAMILIA ON (FAMILIA.CODFAM = ARTICULOS.CODFAM)
  					LEFT JOIN D_SECCIONES_TBL SECCION ON (SECCION.CODSECCION = ARTICULOS.CODSECCION)
	 					LEFT JOIN D_CATEGORIZACION_TBL CAT ON (CAT.CODCAT = ARTICULOS.CODCAT)
	 					LEFT JOIN D_PROVEEDORES_TBL PROV ON (PROV.CODPRO = ARTICULOS.CODPRO)
	 					LEFT JOIN CONFIG_IMP_TIPOS_TBL IMP ON (IMP.CODIMP = ARTICULOS.CODIMP)
	 					LEFT JOIN D_PROVEEDORES_TBL FABRICANTE ON (FABRICANTE.CODPRO = ARTICULOS.CODFAB AND FABRICANTE.TIPO_PROVEEDOR = 'FAB')
;
CREATE OR REPLACE VIEW D_ARTICULOS_CODBAR (
   CODART,
   DESGLOSE1,
   DESGLOSE2 )
AS
SELECT DISTINCT a.codart, a.desglose1, a.desglose2
  FROM d_articulos_codbar_tbl a
;
CREATE OR REPLACE VIEW D_ARTICULOS_TV (
   CODART,
   DESART,
   CODFAM,
   CODSECCION,
   CODCAT,
   CODPRO,
   REFERENCIA_PROVEEDOR,
   ACTIVO,
   OBSERVACIONES,
   ESCAPARATE,
   FECHA_ALTA )
AS
SELECT  ARTICULOS.CODART, ARTICULOS.DESART, ARTICULOS.CODFAM,
        ARTICULOS.CODSECCION, ARTICULOS.CODCAT, 
        ARTICULOS.CODPRO, ARTICULOS.REFERENCIA_PROVEEDOR,
        ARTICULOS.ACTIVO, ARTICULOS.OBSERVACIONES, ARTICULOS.ESCAPARATE, ARTICULOS.FECHA_ALTA
FROM D_ARTICULOS_TBL ARTICULOS
;
CREATE OR REPLACE VIEW D_CATEGORIZACION (
   CODCAT,
   DESCAT,
   CODCAT_PADRE,
   ACTIVO )
AS
SELECT CODCAT, DESCAT, SUBSTR(CODCAT, 1, 2) CODCAT_PADRE, ACTIVO
FROM D_CATEGORIZACION_TBL
WHERE  LENGTH(CODCAT) <= 4
ORDER BY CODCAT
;
CREATE OR REPLACE VIEW D_CLIE_ALBARANES_CAB (
   ID_CLIE_ALBARAN,
   CODEMP,
   PERIODO,
   CODSERIE,
   DESSERIE,
   NUMALB,
   FECHA,
   FECHA_SUMINISTRO,
   CODALM,
   DESALM,
   CODCAJA,
   UID_DIARIO_CAJA,
   CODAPLICACION,
   CODCONALM,
   DESCONALM,
   CODCLI,
   DESCLI,
   REFERENCIA_CLIENTE,
   CODTAR,
   DESTAR,
   PERSONA_CONTACTO,
   ID_GRUPO_IMPUESTOS,
   ID_TRAT_IMPUESTOS,
   DESTRATIMP,
   BASE,
   IMPUESTOS,
   TOTAL,
   OBSERVACIONES,
   ID_USUARIO,
   ID_FACTURA_SOP,
   ID_FACTURA_REP,
   TARJETA_FIDELIZACION,
   UID_TICKET,
   CODSERIE_FACTURA,
   NUMFAC,
   FECHA_FACTURA,
   TRACKING_PORTE )
AS
SELECT ALBARANES_CAB.ID_CLIE_ALBARAN,
       ALBARANES_CAB.CODEMP,
       ALBARANES_CAB.PERIODO,
       ALBARANES_CAB.CODSERIE,
       SERIES.DESSERIE,
       ALBARANES_CAB.NUMALB,
       ALBARANES_CAB.FECHA,
       ALBARANES_CAB.FECHA_SUMINISTRO,
							ALBARANES_CAB.CODALM,
       ALMACENES.DESALM,
							ALBARANES_CAB.CODCAJA,
       ALBARANES_CAB.UID_DIARIO_CAJA,
       ALBARANES_CAB.CODAPLICACION,
       ALBARANES_CAB.CODCONALM,
       CONCEPTOS.DESCONALM,
       ALBARANES_CAB.CODCLI,
       CLIENTES.DESCLI,
       ALBARANES_CAB.REFERENCIA_CLIENTE,
       ALBARANES_CAB.CODTAR,
       TARIFAS.DESTAR,
							ALBARANES_CAB.PERSONA_CONTACTO,
       ALBARANES_CAB.ID_GRUPO_IMPUESTOS,
       ALBARANES_CAB.ID_TRAT_IMPUESTOS,
       TRAT_IMP.DESTRATIMP,
       ALBARANES_CAB.BASE,
       ALBARANES_CAB.IMPUESTOS,
       ALBARANES_CAB.TOTAL,
       ALBARANES_CAB.OBSERVACIONES,
       ALBARANES_CAB.ID_USUARIO,
	      ALBARANES_CAB.ID_FACTURA_SOP,
       ALBARANES_CAB.ID_FACTURA_REP,
							ALBARANES_CAB.TARJETA_FIDELIZACION,
							ALBARANES_CAB.UID_TICKET,
							FACTURAS.CODSERIE CODSERIE_FACTURA,
							FACTURAS.NUMFAC,
							FACTURAS.FECHA FECHA_FACTURA,
							ALBARANES_CAB.TRACKING_PORTE
  FROM D_CLIE_ALBARANES_CAB_TBL ALBARANES_CAB
     INNER JOIN D_SERIES_TBL SERIES ON (SERIES.CODSERIE = ALBARANES_CAB.CODSERIE)
     INNER JOIN D_ALMACENES_TBL ALMACENES ON (ALMACENES.CODALM = ALBARANES_CAB.CODALM)
     INNER JOIN D_ALMACENES_CONCEPTOS_TBL CONCEPTOS ON (CONCEPTOS.CODAPLICACION = ALBARANES_CAB.CODAPLICACION
   																																																	AND CONCEPTOS.CODCONALM = ALBARANES_CAB.CODCONALM)
     INNER JOIN D_CLIENTES_TBL CLIENTES ON (CLIENTES.CODCLI = ALBARANES_CAB.CODCLI)
     LEFT JOIN D_TARIFAS_CAB_TBL TARIFAS ON (TARIFAS.CODTAR = ALBARANES_CAB.CODTAR)
     LEFT JOIN D_FACTURAS_REP_CAB_TBL FACTURAS ON (FACTURAS.ID_FACTURA_REP = ALBARANES_CAB.ID_FACTURA_REP)
					LEFT JOIN CONFIG_IMP_TRATAMIENTO_TBL TRAT_IMP ON (TRAT_IMP.ID_TRAT_IMPUESTOS = ALBARANES_CAB.ID_TRAT_IMPUESTOS)
;
CREATE OR REPLACE VIEW D_CLIE_ALBARANES_DET (
   ID_CLIE_ALBARAN,
   LINEA,
   FECHA,
   CODART,
   DESGLOSE1,
   DESGLOSE2,
   DESART,
   DESCRIPCION_AMPLIADA,
   UNIDAD_MEDIDA,
   CANTIDAD_MEDIDA,
   CANTIDAD,
   PRECIO,
   PRECIO_TOTAL,
   DESCUENTO,
   IMPORTE,
   IMPORTE_TOTAL,
   PRECIO_COSTO,
   CODIMP,
   ID_CLIE_PEDIDO,
   PEDIDO_LINEA )
AS
SELECT ALBARANES_DET.ID_CLIE_ALBARAN,
       ALBARANES_DET.LINEA,
       ALBARANES_DET.FECHA,
       ALBARANES_DET.CODART,
       ALBARANES_DET.DESGLOSE1,
       ALBARANES_DET.DESGLOSE2,
       ALBARANES_DET.DESART,
       ALBARANES_DET.DESCRIPCION_AMPLIADA,
       ALBARANES_DET.UNIDAD_MEDIDA,
       ALBARANES_DET.CANTIDAD_MEDIDA,
       ALBARANES_DET.CANTIDAD,
       ALBARANES_DET.PRECIO,
       ALBARANES_DET.PRECIO_TOTAL,
       ALBARANES_DET.DESCUENTO,
       ALBARANES_DET.IMPORTE,
       ALBARANES_DET.IMPORTE_TOTAL,
       ALBARANES_DET.PRECIO_COSTO,
       ALBARANES_DET.CODIMP,
       ALBARANES_DET.ID_CLIE_PEDIDO,
       ALBARANES_DET.PEDIDO_LINEA
  FROM D_CLIE_ALBARANES_DET_TBL ALBARANES_DET
;
CREATE OR REPLACE VIEW D_CLIE_ALBARANES_PAG (
   ID_CLIE_ALBARAN,
   LINEA,
   ID_MEDPAG_VEN,
   DESMEDPAG_VEN,
   IMPORTE,
   NUMERO_OPERACION )
AS
SELECT PAGOS.ID_CLIE_ALBARAN,
       PAGOS.LINEA,
       PAGOS.ID_MEDPAG_VEN,
       VENCIMIENTOS.DESMEDPAG_VEN,
       PAGOS.IMPORTE,
       PAGOS.NUMERO_OPERACION
  FROM D_CLIE_ALBARANES_PAG_TBL PAGOS
       INNER JOIN D_MEDIOS_PAGO_VEN_TBL VENCIMIENTOS ON VENCIMIENTOS.ID_MEDPAG_VEN = PAGOS.ID_MEDPAG_VEN
;
CREATE OR REPLACE VIEW D_CLIE_PEDIDOS_CAB (
   ID_CLIE_PEDIDO,
   CODEMP,
   PERIODO,
   CODSERIE,
   DESSERIE,
   NUMPED,
   FECHA,
   FECHA_SUMINISTRO_PREV,
   CODALM,
   DESALM,
   CODCAJA,
   UID_DIARIO_CAJA,
   CODAPLICACION,
   CODCONALM,
   DESCONALM,
   CODCLI,
   DESCLI,
   CODTAR,
   DESTAR,
   ID_TIPO_PORTE,
   PERSONA_CONTACTO,
   REFERENCIA_CLIENTE,
   ID_GRUPO_IMPUESTOS,
   ID_TRAT_IMPUESTOS,
   DESTRATIMP,
   BASE,
   IMPUESTOS,
   TOTAL,
   OBSERVACIONES,
   ID_USUARIO,
   TARJETA_FIDELIZACION,
   ESTADO,
   SUBESTADO,
   DESESTADO,
   ESTADO_RECEPTOR,
   SUBESTADO_RECEPTOR,
   DESESTADO_RECEPTOR,
   ID_CLIE_PRESUPUESTO,
   URL_TRACKING )
AS
SELECT PEDIDOS_CAB.ID_CLIE_PEDIDO,
       PEDIDOS_CAB.CODEMP,
       PEDIDOS_CAB.PERIODO,
       PEDIDOS_CAB.CODSERIE,
       SERIES.DESSERIE,
       PEDIDOS_CAB.NUMPED,
       PEDIDOS_CAB.FECHA,
       PEDIDOS_CAB.FECHA_SUMINISTRO_PREV,
       PEDIDOS_CAB.CODALM,
       ALMACENES.DESALM,
       PEDIDOS_CAB.CODCAJA,
       PEDIDOS_CAB.UID_DIARIO_CAJA,
       PEDIDOS_CAB.CODAPLICACION,
       PEDIDOS_CAB.CODCONALM,
       ALMACENES_CONCEPTOS.DESCONALM,
       PEDIDOS_CAB.CODCLI,
       CLIENTES.DESCLI,
       PEDIDOS_CAB.CODTAR,
       TARIFAS.DESTAR,
       PEDIDOS_CAB.ID_TIPO_PORTE,
       PEDIDOS_CAB.PERSONA_CONTACTO,
       PEDIDOS_CAB.REFERENCIA_CLIENTE,
       PEDIDOS_CAB.ID_GRUPO_IMPUESTOS,
       PEDIDOS_CAB.ID_TRAT_IMPUESTOS,
       TRAT_IMP.DESTRATIMP,
       PEDIDOS_CAB.BASE,
       PEDIDOS_CAB.IMPUESTOS,
       PEDIDOS_CAB.TOTAL,
       PEDIDOS_CAB.OBSERVACIONES,
       PEDIDOS_CAB.ID_USUARIO,
       PEDIDOS_CAB.TARJETA_FIDELIZACION,
       PEDIDOS_CAB.ESTADO,
       PEDIDOS_CAB.SUBESTADO,
       ESTADOS_EMISOR.DESESTADO,
       PEDIDOS_CAB.ESTADO_RECEPTOR,
       PEDIDOS_CAB.SUBESTADO_RECEPTOR,
       ESTADOS_RECEPTOR.DESESTADO AS DESESTADO_RECEPTOR,
       PEDIDOS_CAB.ID_CLIE_PRESUPUESTO,
       TIPOS_PORTES.URL_TRACKING
  FROM D_CLIE_PEDIDOS_CAB_TBL PEDIDOS_CAB
       INNER JOIN D_SERIES_TBL SERIES ON PEDIDOS_CAB.CODSERIE = SERIES.CODSERIE
       INNER JOIN D_ALMACENES_TBL ALMACENES ON PEDIDOS_CAB.CODALM = ALMACENES.CODALM
       INNER JOIN D_ALMACENES_CONCEPTOS_TBL ALMACENES_CONCEPTOS ON (ALMACENES_CONCEPTOS.CODAPLICACION = PEDIDOS_CAB.CODAPLICACION
                                                                AND PEDIDOS_CAB.CODCONALM = ALMACENES_CONCEPTOS.CODCONALM)
       INNER JOIN D_CLIENTES_TBL CLIENTES ON PEDIDOS_CAB.CODCLI = CLIENTES.CODCLI
       LEFT JOIN D_TARIFAS_CAB_TBL TARIFAS ON PEDIDOS_CAB.CODTAR = TARIFAS.CODTAR
       INNER JOIN CONFIG_ESTADOS_TBL ESTADOS_EMISOR ON (ESTADOS_EMISOR.PROCESO = 'PEDCLI'
                                                    AND ESTADOS_EMISOR.ESTADO = PEDIDOS_CAB.ESTADO)
       INNER JOIN CONFIG_ESTADOS_TBL ESTADOS_RECEPTOR ON (ESTADOS_RECEPTOR.PROCESO = 'PEDCLI_RECEPTOR'
                                                      AND ESTADOS_RECEPTOR.ESTADO = PEDIDOS_CAB.ESTADO_RECEPTOR)
							LEFT JOIN CONFIG_IMP_TRATAMIENTO_TBL TRAT_IMP ON (PEDIDOS_CAB.ID_TRAT_IMPUESTOS = TRAT_IMP.ID_TRAT_IMPUESTOS)
       LEFT JOIN D_TIPOS_PORTES_TBL TIPOS_PORTES ON PEDIDOS_CAB.ID_TIPO_PORTE = TIPOS_PORTES.ID_TIPO_PORTE
;
CREATE OR REPLACE VIEW D_CLIE_PEDIDOS_DET (
   ID_CLIE_PEDIDO,
   LINEA,
   CODART,
   DESART,
   UNIDAD_MEDIDA_ALTERNATIVA,
   DESGLOSE1,
   DESGLOSE2,
   DESCRIPCION_AMPLIADA,
   UNIDAD_MEDIDA,
   CANTIDAD_MEDIDA_SOLICITADA,
   CANTIDAD_SOLICITADA,
   CANTIDAD_MEDIDA_ACEPTADA,
   CANTIDAD_ACEPTADA,
   CANTIDAD_MEDIDA_PREPARADA,
   CANTIDAD_PREPARADA,
   PRECIO,
   DESCUENTO,
   IMPORTE,
   CODIMP,
   ID_PROMOCION,
   LESTADO,
   LSUBESTADO,
   LDESESTADO,
   ID_CLIE_PEDIDO_ORIGEN,
   LINEA_PEDIDO_ORIGEN )
AS
SELECT PEDIDOS_DET.ID_CLIE_PEDIDO,
       PEDIDOS_DET.LINEA,
       PEDIDOS_DET.CODART,
       PEDIDOS_DET.DESART,
       ARTICULOS.UNIDAD_MEDIDA_ALTERNATIVA,
       PEDIDOS_DET.DESGLOSE1,
       PEDIDOS_DET.DESGLOSE2,
       PEDIDOS_DET.DESCRIPCION_AMPLIADA,
       PEDIDOS_DET.UNIDAD_MEDIDA,
       PEDIDOS_DET.CANTIDAD_MEDIDA_SOLICITADA,
       PEDIDOS_DET.CANTIDAD_SOLICITADA,
       PEDIDOS_DET.CANTIDAD_MEDIDA_ACEPTADA,
       PEDIDOS_DET.CANTIDAD_ACEPTADA,
       PEDIDOS_DET.CANTIDAD_MEDIDA_PREPARADA,
       PEDIDOS_DET.CANTIDAD_PREPARADA,
       PEDIDOS_DET.PRECIO,
       PEDIDOS_DET.DESCUENTO,
       PEDIDOS_DET.IMPORTE,
       PEDIDOS_DET.CODIMP,
       PEDIDOS_DET.ID_PROMOCION,
       PEDIDOS_DET.LESTADO,
       PEDIDOS_DET.LSUBESTADO,
       ESTADOS.DESESTADO AS LDESESTADO,
       PEDIDOS_DET.ID_CLIE_PEDIDO_ORIGEN,
       PEDIDOS_DET.LINEA_PEDIDO_ORIGEN
  FROM D_CLIE_PEDIDOS_DET_TBL PEDIDOS_DET
       INNER JOIN D_ARTICULOS_TBL ARTICULOS ON (ARTICULOS.CODART = PEDIDOS_DET.CODART)
       LEFT JOIN CONFIG_ESTADOS_TBL ESTADOS ON (ESTADOS.PROCESO = 'PEDCLI_LINEA'
                                             AND ESTADOS.ESTADO = PEDIDOS_DET.LESTADO
                                             AND ESTADOS.SUBESTADO = PEDIDOS_DET.LSUBESTADO)
;
CREATE OR REPLACE VIEW D_CLIE_PEDIDOS_PAG (
   ID_CLIE_PEDIDO,
   LINEA,
   ID_MEDPAG_VEN,
   DESMEDPAG_VEN,
   IMPORTE,
   NUMERO_OPERACION )
AS
SELECT PAGOS.ID_CLIE_PEDIDO,
       PAGOS.LINEA,
       PAGOS.ID_MEDPAG_VEN,
       VENCIMIENTOS.DESMEDPAG_VEN,
       PAGOS.IMPORTE,
       PAGOS.NUMERO_OPERACION
  FROM D_CLIE_PEDIDOS_PAG_TBL PAGOS
       INNER JOIN D_MEDIOS_PAGO_VEN_TBL VENCIMIENTOS ON VENCIMIENTOS.ID_MEDPAG_VEN = PAGOS.ID_MEDPAG_VEN
;
CREATE OR REPLACE VIEW D_CLIENTES (
   CODCLI,
   DESCLI,
   NOMBRE_COMERCIAL,
   DOMICILIO,
   POBLACION,
   PROVINCIA,
   CP,
   TELEFONO1,
   TELEFONO2,
   FAX,
   CODPAIS,
   DESPAIS,
   PERSONA_CONTACTO,
   EMAIL,
   CIF,
   ID_TRAT_IMPUESTOS,
   CODTRATIMP,
   DESTRATIMP,
   ID_MEDPAG_VEN,
   DESMEDPAG_VEN,
   CODMEDPAG,
   CODTAR,
   DESTAR,
   CODSEC,
   DESSEC,
   BANCO,
   BANCO_DOMICILIO,
   BANCO_POBLACION,
   CCC,
   OBSERVACIONES,
   ACTIVO,
   FECHA_ALTA,
   FECHA_BAJA,
   CODALM_TIENDA,
   DESALM_TIENDA,
   RIESGO_CONCEDIDO )
AS
SELECT	CLIENTES.CODCLI, CLIENTES.DESCLI, CLIENTES.NOMBRE_COMERCIAL, CLIENTES.DOMICILIO,
							CLIENTES.POBLACION, CLIENTES.PROVINCIA, CLIENTES.CP, CLIENTES.TELEFONO1,
							CLIENTES.TELEFONO2, CLIENTES.FAX, CLIENTES.CODPAIS, PAISES.DESPAIS,
							CLIENTES.PERSONA_CONTACTO, CLIENTES.EMAIL, CLIENTES.CIF, CLIENTES.ID_TRAT_IMPUESTOS,
							TRATIMP.CODTRATIMP, TRATIMP.DESTRATIMP, 
							CLIENTES.ID_MEDPAG_VEN, MEDPAG_VEN.DESMEDPAG_VEN, MEDPAG_VEN.CODMEDPAG, CLIENTES.CODTAR, TARIFAS.DESTAR,
							CLIENTES.CODSEC, SECTORES.DESSEC, CLIENTES.BANCO, CLIENTES.BANCO_DOMICILIO,
							CLIENTES.BANCO_POBLACION, CLIENTES.CCC, CLIENTES.OBSERVACIONES, CLIENTES.ACTIVO,
							CLIENTES.FECHA_ALTA, CLIENTES.FECHA_BAJA, ALMACENES.CODALM AS CODALM_TIENDA,
       ALMACENES.DESALM AS DESALM_TIENDA, CLIENTES.RIESGO_CONCEDIDO
		FROM D_CLIENTES_TBL CLIENTES
							LEFT JOIN D_PAISES_TBL PAISES ON (CLIENTES.CODPAIS = PAISES.CODPAIS)
							LEFT JOIN CONFIG_IMP_TRATAMIENTO_TBL TRATIMP ON (CLIENTES.ID_TRAT_IMPUESTOS = TRATIMP.ID_TRAT_IMPUESTOS)
							LEFT JOIN D_MEDIOS_PAGO_VEN_TBL MEDPAG_VEN ON (MEDPAG_VEN.ID_MEDPAG_VEN = CLIENTES.ID_MEDPAG_VEN)
							LEFT JOIN D_TARIFAS_CAB_TBL TARIFAS ON (CLIENTES.CODTAR = TARIFAS.CODTAR)
							LEFT JOIN D_SECTORES_TBL SECTORES ON (CLIENTES.CODSEC = SECTORES.CODSEC)
							LEFT JOIN D_ALMACENES_TBL ALMACENES ON (CLIENTES.CODCLI = ALMACENES.CODCLI)
;
CREATE OR REPLACE VIEW D_COBROS (
   ID_COBRO,
   ID_COBRO_DEVOLUCION,
   CODEMP,
   CODCLI,
   DESCLI,
   FECHA_ALTA,
   FECHA_VENCIMIENTO,
   FECHA_FACTURA,
   FECHA_BAJA,
   CODTIPOEFEC,
   DESTIPOEFEC,
   CODSERIE,
   DOCUMENTO,
   CODBAN_COBRO,
   DESBAN_COBRO,
   FECHA_COBRO,
   IMPORTE,
   OBSERVACIONES,
   GASTOS_DEVOLUCION,
   CODBAN_DEVOLUCION,
   REMESABLE,
   FECHA_ENTRADA_DOCUMENTO,
   ID_REMESA,
   CODBAN_REMESA,
   DESBAN_REMESA,
   FECHA_REMESA,
   BORRADO,
   RIESGO_CONCEDIDO )
AS
SELECT
     COBROS.ID_COBRO,
     COBROS.ID_COBRO_DEVOLUCION,
     COBROS.CODEMP,
     COBROS.CODCLI,
     CLIENTES.DESCLI,
     COBROS.FECHA_ALTA,
     COBROS.FECHA_VENCIMIENTO,
     (SELECT MIN(FECHA_FACTURA) FROM D_COBROS_VEN_TBL VEN WHERE VEN.ID_COBRO = COBROS.ID_COBRO) FECHA_FACTURA,
     COBROS.FECHA_BAJA,
     COBROS.CODTIPOEFEC,
     TIPOS_EFECTOS.DESTIPOEFEC,
     COBROS.CODSERIE,
     COBROS.DOCUMENTO,
     COBROS.CODBAN_COBRO,
     BANCOS_COBROS.DESBAN DESBAN_COBRO,
     COBROS.FECHA_COBRO,
     COBROS.IMPORTE,
     COBROS.OBSERVACIONES,
     COBROS.GASTOS_DEVOLUCION,
     COBROS.CODBAN_DEVOLUCION,
     COBROS.REMESABLE,
     COBROS.FECHA_ENTRADA_DOCUMENTO,
     COBROS.ID_REMESA,
     REMESAS.CODBAN CODBAN_REMESA,
     BANCOS.DESBAN DESBAN_REMESA,
     REMESAS.FECHA_REMESA,
     COBROS.BORRADO,
     CLIENTES.RIESGO_CONCEDIDO
FROM
     D_COBROS_DOC_TBL COBROS
        INNER JOIN D_CLIENTES_TBL CLIENTES ON CLIENTES.CODCLI = COBROS.CODCLI
        INNER JOIN D_TIPOS_EFECTOS_TBL TIPOS_EFECTOS ON TIPOS_EFECTOS.CODTIPOEFEC = COBROS.CODTIPOEFEC
        LEFT JOIN D_COBROS_REMESAS_CAB_TBL REMESAS ON REMESAS.ID_REMESA = COBROS.ID_REMESA
        LEFT JOIN D_BANCOS_TBL BANCOS ON BANCOS.CODBAN = REMESAS.CODBAN
        LEFT JOIN D_BANCOS_TBL BANCOS_COBROS ON BANCOS_COBROS.CODBAN = COBROS.CODBAN_COBRO
;
CREATE OR REPLACE VIEW D_COBROS_REMESAS_CAB (
   ID_REMESA,
   FECHA_REMESA,
   CODBAN,
   ESTADO,
   DESESTADO,
   DESBAN,
   EFECTOS,
   CLIENTES,
   DEVUELTOS,
   IMPORTE )
AS
SELECT CAB.ID_REMESA,
       CAB.FECHA_REMESA,
       CAB.CODBAN,
       CAB.ESTADO,
       EST.DESESTADO,
       BAN.DESBAN,
       (SELECT COUNT(*) FROM D_COBROS_DOC_TBL WHERE ID_REMESA = CAB.ID_REMESA) EFECTOS,
       (SELECT COUNT( DISTINCT CODCLI) FROM D_COBROS_DOC_TBL WHERE ID_REMESA = CAB.ID_REMESA) CLIENTES,
       (SELECT COUNT(*) FROM D_COBROS_DOC_TBL WHERE ID_REMESA = CAB.ID_REMESA AND CODBAN_DEVOLUCION IS NOT NULL) DEVUELTOS,
       (SELECT SUM(IMPORTE) FROM D_COBROS_DOC_TBL WHERE ID_REMESA = CAB.ID_REMESA) IMPORTE
FROM D_COBROS_REMESAS_CAB_TBL CAB
     INNER JOIN D_BANCOS_TBL BAN ON (BAN.CODBAN = CAB.CODBAN)
					INNER JOIN CONFIG_ESTADOS_TBL EST ON (EST.ESTADO = CAB.ESTADO
																																											AND EST.PROCESO = 'REMESA_COBRO')
;
CREATE OR REPLACE VIEW D_CONSULTA_ARTICULOS (
   CODART,
   DESART,
   CODFAM,
   DESFAM,
   CODPRO,
   DESPRO,
   ACTIVO,
   CODCAT,
   DESCAT,
   CODSECCION,
   DESSECCION,
   REFERENCIA_PROVEEDOR )
AS
SELECT	ARTICULOS.CODART, ARTICULOS.DESART, ARTICULOS.CODFAM, FAMILIAS.DESFAM,
        ARTICULOS.CODPRO, PROVEEDORES.DESPRO, ARTICULOS.ACTIVO, CAT.CODCAT,
        CAT.DESCAT, SECCION.CODSECCION, SECCION.DESSECCION, ARTICULOS.REFERENCIA_PROVEEDOR
FROM D_ARTICULOS_TBL ARTICULOS
        LEFT JOIN D_FAMILIAS_TBL FAMILIAS ON (ARTICULOS.CODFAM = FAMILIAS.CODFAM)
        LEFT JOIN D_PROVEEDORES_TBL PROVEEDORES ON (ARTICULOS.CODPRO = PROVEEDORES.CODPRO)
        LEFT JOIN D_SECCIONES_TBL SECCION ON (SECCION.CODSECCION = ARTICULOS.CODSECCION)
        LEFT JOIN D_CATEGORIZACION_TBL CAT ON (CAT.CODCAT = ARTICULOS.CODCAT)
;
CREATE OR REPLACE VIEW D_FABRICANTES (
   CODPRO,
   DESPRO )
AS
SELECT PROV.CODPRO, PROV.DESPRO
 	FROM D_PROVEEDORES_TBL PROV
 	WHERE PROV.TIPO_PROVEEDOR = 'FAB'
;
CREATE OR REPLACE VIEW D_FACTURAS_REP_CAB (
   ID_FACTURA_REP,
   CODEMP,
   PERIODO,
   CODSERIE,
   DESSERIE,
   NUMFAC,
   REFERENCIA,
   FECHA,
   CODCLI,
   DESCLI,
   DOMICILIO,
   POBLACION,
   PROVINCIA,
   CP,
   CIF,
   ID_GRUPO_IMPUESTOS,
   ID_TRAT_IMPUESTOS,
   ID_VENCIMIENTO_ENLACE,
   CONCEPTO,
   BASE,
   IMPUESTOS,
   TOTAL,
   OBSERVACIONES )
AS
SELECT FACTURAS.ID_FACTURA_REP, FACTURAS.CODEMP, FACTURAS.PERIODO, FACTURAS.CODSERIE, SERIES.DESSERIE,
FACTURAS.NUMFAC, FACTURAS.REFERENCIA, FACTURAS.FECHA, CODCLI, FACTURAS.DESCLI, FACTURAS.DOMICILIO,
FACTURAS.POBLACION, FACTURAS.PROVINCIA, FACTURAS.CP, FACTURAS.CIF, 
FACTURAS.ID_GRUPO_IMPUESTOS, FACTURAS.ID_TRAT_IMPUESTOS, FACTURAS.ID_VENCIMIENTO_ENLACE,
FACTURAS.CONCEPTO, FACTURAS.BASE, FACTURAS.IMPUESTOS, FACTURAS.TOTAL, FACTURAS.OBSERVACIONES
FROM D_FACTURAS_REP_CAB_TBL FACTURAS
LEFT JOIN D_SERIES_TBL SERIES ON (FACTURAS.CODSERIE = SERIES.CODSERIE)
;
CREATE OR REPLACE VIEW D_FACTURAS_REP_COB (
   ID_VENCIMIENTO_ENLACE,
   ID_VENCIMIENTO,
   ID_COBRO,
   IMPORTE,
   FECHA_ALTA,
   FECHA_VENCIMIENTO,
   FECHA_VENCIMIENTO_DOCUMENTO,
   FECHA_BAJA_DOCUMENTO,
   CODTIPOEFEC,
   DESTIPOEFEC,
   CODSERIE,
   DOCUMENTO,
   CODBAN_COBRO,
   FECHA_COBRO,
   IMPORTE_DOCUMENTO,
   OBSERVACIONES,
   BORRADO,
   ID_REMESA,
   CODBAN_REMESA,
   FECHA_REMESA )
AS
SELECT
     D_COBROS_VEN_TBL.ID_VENCIMIENTO_ENLACE,
     D_COBROS_VEN_TBL.ID_VENCIMIENTO,
     D_COBROS_VEN_TBL.ID_COBRO,
     D_COBROS_VEN_TBL.IMPORTE,
     D_COBROS_VEN_TBL.FECHA_ALTA,
     D_COBROS_VEN_TBL.FECHA_VENCIMIENTO,
     D_COBROS_DOC_TBL.FECHA_VENCIMIENTO AS FECHA_VENCIMIENTO_DOCUMENTO,
     D_COBROS_DOC_TBL.FECHA_BAJA AS FECHA_BAJA_DOCUMENTO,
     D_COBROS_DOC_TBL.CODTIPOEFEC,
     D_TIPOS_EFECTOS_TBL.DESTIPOEFEC,
     D_COBROS_DOC_TBL.CODSERIE,
     D_COBROS_DOC_TBL.DOCUMENTO,
     D_COBROS_DOC_TBL.CODBAN_COBRO,
     D_COBROS_DOC_TBL.FECHA_COBRO,
     D_COBROS_DOC_TBL.IMPORTE AS IMPORTE_DOCUMENTO,
     D_COBROS_DOC_TBL.OBSERVACIONES,
     D_COBROS_DOC_TBL.BORRADO,
     D_COBROS_DOC_TBL.ID_REMESA,
     D_COBROS_REMESAS_CAB_TBL.CODBAN AS CODBAN_REMESA,
     D_COBROS_REMESAS_CAB_TBL.FECHA_REMESA
FROM
     D_COBROS_DOC_TBL D_COBROS_DOC_TBL
        INNER JOIN D_COBROS_VEN_TBL D_COBROS_VEN_TBL ON D_COBROS_DOC_TBL.ID_COBRO = D_COBROS_VEN_TBL.ID_COBRO
        INNER JOIN D_TIPOS_EFECTOS_TBL D_TIPOS_EFECTOS_TBL ON D_COBROS_DOC_TBL.CODTIPOEFEC = D_TIPOS_EFECTOS_TBL.CODTIPOEFEC
        LEFT OUTER JOIN D_COBROS_REMESAS_CAB_TBL D_COBROS_REMESAS_CAB_TBL ON D_COBROS_DOC_TBL.ID_REMESA = D_COBROS_REMESAS_CAB_TBL.ID_REMESA
;
CREATE OR REPLACE VIEW D_FACTURAS_REP_DET (
   ID_FACTURA_REP,
   LINEA,
   REFERENCIA,
   FECHA_REFERENCIA,
   CODART,
   DESGLOSE1,
   DESGLOSE2,
   CONCEPTO,
   CONCEPTO_AMPLIADO,
   UNIDAD_MEDIDA,
   DESUNIDAD_MEDIDA,
   CANTIDAD_MEDIDA,
   CANTIDAD,
   PRECIO,
   IMPORTE,
   CODIMP,
   DESIMP )
AS
SELECT FACTURA_REP_DET.ID_FACTURA_REP,
       FACTURA_REP_DET.LINEA,
       FACTURA_REP_DET.REFERENCIA,
       FACTURA_REP_DET.FECHA_REFERENCIA,
       FACTURA_REP_DET.CODART,
       FACTURA_REP_DET.DESGLOSE1,
       FACTURA_REP_DET.DESGLOSE2,
       FACTURA_REP_DET.CONCEPTO,
       FACTURA_REP_DET.CONCEPTO_AMPLIADO,
       FACTURA_REP_DET.UNIDAD_MEDIDA,
       UNIDADES.DES_UM_ETIQUETA,
       FACTURA_REP_DET.CANTIDAD_MEDIDA,
       FACTURA_REP_DET.CANTIDAD,
       FACTURA_REP_DET.PRECIO,
       FACTURA_REP_DET.IMPORTE,
       FACTURA_REP_DET.CODIMP,
       TIPOS_IMPUESTOS.DESIMP
FROM D_FACTURAS_REP_DET_TBL FACTURA_REP_DET
     LEFT JOIN CONFIG_IMP_TIPOS_TBL TIPOS_IMPUESTOS ON (FACTURA_REP_DET.CODIMP = TIPOS_IMPUESTOS.CODIMP)
     LEFT JOIN D_UNIDAD_MEDIDA_ETIQUETAS_TBL UNIDADES ON (FACTURA_REP_DET.UNIDAD_MEDIDA = UNIDADES.COD_UM_ETIQUETA)
;
CREATE OR REPLACE VIEW D_FACTURAS_REP_PAG (
   ID_FACTURA_REP,
   LINEA,
   ID_MEDPAG_VEN,
   DESMEDPAG_VEN,
   IMPORTE )
AS
SELECT PAGOS.ID_FACTURA_REP,
       PAGOS.LINEA,
       PAGOS.ID_MEDPAG_VEN,
       MEDIOS_PAGO_VEN.DESMEDPAG_VEN,
       PAGOS.IMPORTE
  FROM D_FACTURAS_REP_PAG_TBL PAGOS
     LEFT JOIN D_MEDIOS_PAGO_VEN_TBL MEDIOS_PAGO_VEN ON (MEDIOS_PAGO_VEN.ID_MEDPAG_VEN = PAGOS.ID_MEDPAG_VEN)
;
CREATE OR REPLACE VIEW D_FACTURAS_SOP_CAB (
   ID_FACTURA_SOP,
   CODEMP,
   PERIODO,
   CODSERIE,
   DESSERIE,
   NUMFAC,
   REFERENCIA,
   FECHA,
   FECHA_FACT_PROVEEDOR,
   CODPRO,
   DESPRO,
   DOMICILIO,
   POBLACION,
   PROVINCIA,
   CP,
   CIF,
   ID_GRUPO_IMPUESTOS,
   ID_TRAT_IMPUESTOS,
   ID_VENCIMIENTO_ENLACE,
   CONCEPTO,
   BASE,
   IMPUESTOS,
   TOTAL,
   OBSERVACIONES )
AS
SELECT FACTURAS.ID_FACTURA_SOP, FACTURAS.CODEMP, FACTURAS.PERIODO, FACTURAS.CODSERIE, SERIES.DESSERIE,
							FACTURAS.NUMFAC, FACTURAS.REFERENCIA, FACTURAS.FECHA, FACTURAS.FECHA_FACT_PROVEEDOR,
							FACTURAS.CODPRO, FACTURAS.DESPRO, FACTURAS.DOMICILIO,
							FACTURAS.POBLACION, FACTURAS.PROVINCIA, FACTURAS.CP, FACTURAS.CIF,
							FACTURAS.ID_GRUPO_IMPUESTOS, FACTURAS.ID_TRAT_IMPUESTOS, FACTURAS.ID_VENCIMIENTO_ENLACE,
							FACTURAS.CONCEPTO, FACTURAS.BASE, FACTURAS.IMPUESTOS, FACTURAS.TOTAL, FACTURAS.OBSERVACIONES
		FROM D_FACTURAS_SOP_CAB_TBL FACTURAS
							LEFT JOIN D_SERIES_TBL SERIES ON (FACTURAS.CODSERIE = SERIES.CODSERIE)
;
CREATE OR REPLACE VIEW D_FACTURAS_SOP_DET (
   ID_FACTURA_SOP,
   LINEA,
   REFERENCIA,
   FECHA_REFERENCIA,
   CODART,
   DESGLOSE1,
   DESGLOSE2,
   CONCEPTO,
   CONCEPTO_AMPLIADO,
   UNIDAD_MEDIDA,
   DESUNIDAD_MEDIDA,
   CANTIDAD_MEDIDA,
   CANTIDAD,
   PRECIO,
   IMPORTE,
   CODIMP,
   DESIMP )
AS
SELECT DETALLE.ID_FACTURA_SOP, DETALLE.LINEA, DETALLE.REFERENCIA, DETALLE.FECHA_REFERENCIA, DETALLE.CODART,
        DETALLE.DESGLOSE1, DETALLE.DESGLOSE2, DETALLE.CONCEPTO, DETALLE.CONCEPTO_AMPLIADO, DETALLE.UNIDAD_MEDIDA,
        UNIDADES.DES_UM_ETIQUETA, DETALLE.CANTIDAD_MEDIDA, DETALLE.CANTIDAD, DETALLE.PRECIO,
        DETALLE.IMPORTE, DETALLE.CODIMP, TIPOS_IMPUESTOS.DESIMP
  FROM D_FACTURAS_SOP_DET_TBL DETALLE
     LEFT JOIN CONFIG_IMP_TIPOS_TBL TIPOS_IMPUESTOS ON (DETALLE.CODIMP = TIPOS_IMPUESTOS.CODIMP)
     LEFT JOIN D_UNIDAD_MEDIDA_ETIQUETAS_TBL UNIDADES ON (DETALLE.UNIDAD_MEDIDA = UNIDADES.COD_UM_ETIQUETA)
;
CREATE OR REPLACE VIEW D_FACTURAS_SOP_PAG (
   ID_FACTURA_SOP,
   LINEA,
   ID_MEDPAG_VEN,
   DESMEDPAG_VEN,
   IMPORTE )
AS
SELECT PAGOS.ID_FACTURA_SOP,
       PAGOS.LINEA,
       PAGOS.ID_MEDPAG_VEN,
       MEDIOS_PAGO_VEN.DESMEDPAG_VEN,
       PAGOS.IMPORTE
  FROM D_FACTURAS_SOP_PAG_TBL PAGOS
     LEFT JOIN D_MEDIOS_PAGO_VEN_TBL MEDIOS_PAGO_VEN ON (MEDIOS_PAGO_VEN.ID_MEDPAG_VEN = PAGOS.ID_MEDPAG_VEN)
;
CREATE OR REPLACE VIEW D_MEDIOS_PAGO (
   CODMEDPAG,
   DESMEDPAG,
   CONTADO,
   EFECTIVO,
   TARJETA_CREDITO,
   CODTIPOEFEC,
   DESTIPOEFEC,
   VISIBLE_VENTA,
   VISIBLE_TIENDA_VIRTUAL,
   VISIBLE_COMPRA,
   ACTIVO )
AS
SELECT MEDIOS_PAGO.CODMEDPAG,
       MEDIOS_PAGO.DESMEDPAG,
       MEDIOS_PAGO.CONTADO,
       MEDIOS_PAGO.EFECTIVO,
       MEDIOS_PAGO.TARJETA_CREDITO,
       MEDIOS_PAGO.CODTIPOEFEC,
       TIPOS_EFECTOS.DESTIPOEFEC,
       MEDIOS_PAGO.VISIBLE_VENTA,
       MEDIOS_PAGO.VISIBLE_TIENDA_VIRTUAL,
       MEDIOS_PAGO.VISIBLE_COMPRA,
       MEDIOS_PAGO.ACTIVO
  FROM D_MEDIOS_PAGO_TBL MEDIOS_PAGO
       LEFT JOIN D_TIPOS_EFECTOS_TBL TIPOS_EFECTOS ON TIPOS_EFECTOS.CODTIPOEFEC = MEDIOS_PAGO.CODTIPOEFEC
;
CREATE OR REPLACE VIEW D_MEDIOS_PAGO_VEN (
   ID_MEDPAG_VEN,
   CODMEDPAG,
   DESMEDPAG_VEN,
   NUMERO_VENCIMIENTOS,
   DIAS_CADENCIA,
   DIAS_ENTRE_VENCIMIENTOS,
   DIAS_NATURALES,
   VISIBLE_VENTA,
   VISIBLE_COMPRA,
   ACTIVO )
AS
SELECT VENCIMIENTOS.ID_MEDPAG_VEN,
       VENCIMIENTOS.CODMEDPAG,
       VENCIMIENTOS.DESMEDPAG_VEN,
       VENCIMIENTOS.NUMERO_VENCIMIENTOS,
       VENCIMIENTOS.DIAS_CADENCIA,
       VENCIMIENTOS.DIAS_ENTRE_VENCIMIENTOS,
       VENCIMIENTOS.DIAS_NATURALES,
       MEDIOSPAGO.VISIBLE_VENTA,
       MEDIOSPAGO.VISIBLE_COMPRA,
       VENCIMIENTOS.ACTIVO
  FROM D_MEDIOS_PAGO_VEN_TBL VENCIMIENTOS
       LEFT JOIN D_MEDIOS_PAGO_TBL MEDIOSPAGO ON MEDIOSPAGO.CODMEDPAG = VENCIMIENTOS.CODMEDPAG
;
CREATE OR REPLACE VIEW D_PAGOS (
   ID_PAGO,
   CODEMP,
   CODPRO,
   DESPRO,
   FECHA_ALTA,
   FECHA_VENCIMIENTO,
   FECHA_FACTURA,
   FECHA_BAJA,
   CODTIPOEFEC,
   DESTIPOEFEC,
   CODSERIE,
   DOCUMENTO,
   CODBAN_PAGO,
   DESBAN_PAGO,
   FECHA_PAGO,
   IMPORTE,
   OBSERVACIONES,
   ID_REMESA,
   CODBAN_REMESA,
   DESBAN_REMESA,
   FECHA_REMESA,
   BORRADO,
   FECHA_EMISION )
AS
SELECT
     PAGOS.ID_PAGO,
     PAGOS.CODEMP,
     PAGOS.CODPRO,
     PROVEEDORES.DESPRO,
     PAGOS.FECHA_ALTA,
     PAGOS.FECHA_VENCIMIENTO,
     (SELECT MIN(FECHA_FACTURA) FROM D_PAGOS_VEN_TBL VEN WHERE VEN.ID_PAGO = PAGOS.ID_PAGO) FECHA_FACTURA,
     PAGOS.FECHA_BAJA,
     PAGOS.CODTIPOEFEC,
     TIPOS_EFECTOS.DESTIPOEFEC,
     PAGOS.CODSERIE,
     PAGOS.DOCUMENTO,
     PAGOS.CODBAN_PAGO,
     BANCOS_PAGOS.DESBAN DESBAN_PAGO,
     PAGOS.FECHA_PAGO,
     PAGOS.IMPORTE,
     PAGOS.OBSERVACIONES,
     PAGOS.ID_REMESA,
     REMESAS.CODBAN CODBAN_REMESA,
     BANREME.DESBAN DESBAN_REMESA,
     REMESAS.FECHA_REMESA,
     PAGOS.BORRADO,
     PAGOS.FECHA_EMISION
FROM
     D_PAGOS_DOC_TBL PAGOS
        INNER JOIN D_PROVEEDORES_TBL PROVEEDORES ON PROVEEDORES.CODPRO = PAGOS.CODPRO
        INNER JOIN D_TIPOS_EFECTOS_TBL TIPOS_EFECTOS ON TIPOS_EFECTOS.CODTIPOEFEC = PAGOS.CODTIPOEFEC
        LEFT JOIN D_PAGOS_REMESAS_CAB_TBL REMESAS ON REMESAS.ID_REMESA = PAGOS.ID_REMESA
        LEFT JOIN D_BANCOS_TBL BANREME ON BANREME.CODBAN = REMESAS.CODBAN
        LEFT JOIN D_BANCOS_TBL BANCOS_PAGOS ON BANCOS_PAGOS.CODBAN = PAGOS.CODBAN_PAGO
;
CREATE OR REPLACE VIEW D_PAGOS_REMESAS_CAB (
   ID_REMESA,
   FECHA_REMESA,
   CODBAN,
   DESBAN,
   CODTIPOEFEC,
   DESTIPOEFEC,
   ESTADO,
   DESESTADO,
   EFECTOS,
   PROVEEDORES,
   IMPORTE )
AS
SELECT CAB.ID_REMESA,
       CAB.FECHA_REMESA,
       CAB.CODBAN,
       BAN.DESBAN,
       CAB.CODTIPOEFEC,
       TIPO_EFEC.DESTIPOEFEC,
							CAB.ESTADO,
       EST.DESESTADO,
       (SELECT COUNT(*) FROM D_PAGOS_DOC_TBL WHERE ID_REMESA = CAB.ID_REMESA) EFECTOS,
       (SELECT COUNT( DISTINCT CODPRO) FROM D_PAGOS_DOC_TBL WHERE ID_REMESA = CAB.ID_REMESA) PROVEEDORES,
       (SELECT SUM(IMPORTE) FROM D_PAGOS_DOC_TBL WHERE ID_REMESA = CAB.ID_REMESA) IMPORTE
FROM D_PAGOS_REMESAS_CAB_TBL CAB
     INNER JOIN D_BANCOS_TBL BAN ON (BAN.CODBAN = CAB.CODBAN)
					INNER JOIN D_TIPOS_EFECTOS_TBL TIPO_EFEC ON (TIPO_EFEC.CODTIPOEFEC = CAB.CODTIPOEFEC)
					INNER JOIN CONFIG_ESTADOS_TBL EST ON (EST.ESTADO = CAB.ESTADO
																																											AND EST.PROCESO = 'REMESA_PAGO')
;
CREATE OR REPLACE VIEW D_PROMOCIONES_CAB (
   ID_PROMOCION,
   DESCRIPCION,
   CODTAR,
   DESTAR,
   FECHA_INICIO,
   FECHA_FIN,
   SOLO_FIDELIZACION,
   ID_TIPO_PROMOCION,
   VERSION_TARIFA )
AS
SELECT	PROMOCIONES.ID_PROMOCION, PROMOCIONES.DESCRIPCION, PROMOCIONES.CODTAR,
        TARIFAS.DESTAR, PROMOCIONES.FECHA_INICIO, PROMOCIONES.FECHA_FIN,
        PROMOCIONES.SOLO_FIDELIZACION, PROMOCIONES.ID_TIPO_PROMOCION, PROMOCIONES.VERSION_TARIFA
FROM D_PROMOCIONES_CAB_TBL PROMOCIONES
        LEFT JOIN D_TARIFAS_CAB_TBL TARIFAS ON (PROMOCIONES.CODTAR = TARIFAS.CODTAR)
;
CREATE OR REPLACE VIEW D_PROMOCIONES_DET (
   ID_PROMOCION,
   CODART,
   DESART,
   PRECIO_TARIFA,
   PRECIO_TARIFA_TOTAL,
   PRECIO_VENTA,
   PRECIO_TOTAL,
   VERSION_TARIFA,
   PUNTOS,
   TEXTO_PROMOCION,
   DATOS_PROMOCION,
   FECHA_INICIO,
   FECHA_FIN,
   CODFAM,
   CODPRO,
   CODTAR,
   DESTAR )
AS
SELECT PROMOCIONES.ID_PROMOCION, PROMOCIONES.CODART, ARTICULOS.DESART, PROMOCIONES.PRECIO_TARIFA, PROMOCIONES.PRECIO_TARIFA_TOTAL,
       PROMOCIONES.PRECIO_VENTA, PROMOCIONES.PRECIO_TOTAL, PROMOCIONES.VERSION_TARIFA, PROMOCIONES.PUNTOS,
       PROMOCIONES.TEXTO_PROMOCION, PROMOCIONES.DATOS_PROMOCION,
       PROMOCIONES.FECHA_INICIO, PROMOCIONES.FECHA_FIN, ARTICULOS.CODFAM, ARTICULOS.CODPRO,
       CABECERA.CODTAR, CABECERA.DESCRIPCION AS DESTAR
  FROM D_PROMOCIONES_DET_TBL PROMOCIONES
	   INNER JOIN D_ARTICULOS_TBL ARTICULOS ON (PROMOCIONES.CODART = ARTICULOS.CODART)
       INNER JOIN D_PROMOCIONES_CAB_TBL CABECERA ON (PROMOCIONES.ID_PROMOCION = CABECERA.ID_PROMOCION)
;
CREATE OR REPLACE VIEW D_PROV_ALBARANES_CAB (
   ID_PROV_ALBARAN,
   CODEMP,
   PERIODO,
   CODSERIE,
   DESSERIE,
   CODCONALM,
   DESCONALM,
   CODAPLICACION,
   NUMALB,
   FECHA,
   FECHA_SUMINISTRO,
   REFERENCIA_PROVEEDOR,
   CODPRO,
   DESPRO,
   PERSONA_CONTACTO,
   CODALM,
   DESALM,
   CODCAJA,
   UID_DIARIO_CAJA,
   ID_GRUPO_IMPUESTOS,
   ID_TRAT_IMPUESTOS,
   DESTRATIMP,
   BASE,
   IMPUESTOS,
   TOTAL,
   OBSERVACIONES,
   ID_USUARIO,
   ID_FACTURA_SOP,
   CODSERIE_FACTURA,
   NUMFAC,
   FECHA_FACTURA )
AS
SELECT ALBARANES_CAB.ID_PROV_ALBARAN,
       ALBARANES_CAB.CODEMP,
       ALBARANES_CAB.PERIODO,
       ALBARANES_CAB.CODSERIE,
       SERIES.DESSERIE,
       ALBARANES_CAB.CODCONALM,
       CONCEPTOS.DESCONALM,
       ALBARANES_CAB.CODAPLICACION,
       ALBARANES_CAB.NUMALB,
       ALBARANES_CAB.FECHA,
       ALBARANES_CAB.FECHA_SUMINISTRO,
       ALBARANES_CAB.REFERENCIA_PROVEEDOR,
       ALBARANES_CAB.CODPRO, PROVEEDORES.DESPRO,
							ALBARANES_CAB.PERSONA_CONTACTO,
							ALBARANES_CAB.CODALM,ALMACENES.DESALM,
							ALBARANES_CAB.CODCAJA,
       ALBARANES_CAB.UID_DIARIO_CAJA,
       ALBARANES_CAB.ID_GRUPO_IMPUESTOS,
       ALBARANES_CAB.ID_TRAT_IMPUESTOS,
       TRAT_IMP.DESTRATIMP,
       ALBARANES_CAB.BASE,
       ALBARANES_CAB.IMPUESTOS,
       ALBARANES_CAB.TOTAL,
       ALBARANES_CAB.OBSERVACIONES,
       ALBARANES_CAB.ID_USUARIO,
       ALBARANES_CAB.ID_FACTURA_SOP,
							FACTURAS.CODSERIE CODSERIE_FACTURA,
							FACTURAS.NUMFAC,
							FACTURAS.FECHA FECHA_FACTURA
  FROM D_PROV_ALBARANES_CAB_TBL ALBARANES_CAB
  LEFT JOIN D_SERIES_TBL SERIES ON (ALBARANES_CAB.CODSERIE = SERIES.CODSERIE)
  LEFT JOIN D_PROVEEDORES_TBL PROVEEDORES ON (ALBARANES_CAB.CODPRO = PROVEEDORES.CODPRO)
  LEFT JOIN D_ALMACENES_TBL ALMACENES ON (ALBARANES_CAB.CODALM = ALMACENES.CODALM)
  LEFT JOIN D_ALMACENES_CONCEPTOS_TBL CONCEPTOS ON (ALBARANES_CAB.CODCONALM = CONCEPTOS.CODCONALM
																																																				AND ALBARANES_CAB.CODAPLICACION = CONCEPTOS.CODAPLICACION)
  LEFT JOIN D_FACTURAS_SOP_CAB_TBL FACTURAS ON (ALBARANES_CAB.ID_FACTURA_SOP = FACTURAS.ID_FACTURA_SOP)
  LEFT JOIN CONFIG_IMP_TRATAMIENTO_TBL TRAT_IMP ON (ALBARANES_CAB.ID_TRAT_IMPUESTOS = TRAT_IMP.ID_TRAT_IMPUESTOS)
;
CREATE OR REPLACE VIEW D_PROV_ALBARANES_DET (
   ID_PROV_ALBARAN,
   LINEA,
   FECHA,
   CODART,
   DESGLOSE1,
   DESGLOSE2,
   DESART,
   DESCRIPCION_AMPLIADA,
   UNIDAD_MEDIDA,
   CANTIDAD_MEDIDA,
   CANTIDAD,
   PRECIO,
   DESCUENTO,
   IMPORTE,
   CODIMP,
   ID_PROV_PEDIDO,
   PEDIDO_LINEA )
AS
SELECT ALBARANES_DET.ID_PROV_ALBARAN,
       ALBARANES_DET.LINEA,
       ALBARANES_DET.FECHA,
       ALBARANES_DET.CODART,
       ALBARANES_DET.DESGLOSE1,
       ALBARANES_DET.DESGLOSE2,
       ALBARANES_DET.DESART,
       ALBARANES_DET.DESCRIPCION_AMPLIADA,
       ALBARANES_DET.UNIDAD_MEDIDA,
       ALBARANES_DET.CANTIDAD_MEDIDA,
       ALBARANES_DET.CANTIDAD,
       ALBARANES_DET.PRECIO,
       ALBARANES_DET.DESCUENTO,
       ALBARANES_DET.IMPORTE,
       ALBARANES_DET.CODIMP,
       ALBARANES_DET.ID_PROV_PEDIDO,
       ALBARANES_DET.PEDIDO_LINEA
  FROM D_PROV_ALBARANES_DET_TBL ALBARANES_DET
;
CREATE OR REPLACE VIEW D_PROV_ALBARANES_PAG (
   ID_PROV_ALBARAN,
   LINEA,
   ID_MEDPAG_VEN,
   DESMEDPAG_VEN,
   IMPORTE )
AS
SELECT PAGOS.ID_PROV_ALBARAN,
       PAGOS.LINEA,
       PAGOS.ID_MEDPAG_VEN,
       VENCIMIENTOS.DESMEDPAG_VEN,
       PAGOS.IMPORTE
  FROM D_PROV_ALBARANES_PAG_TBL PAGOS
       INNER JOIN D_MEDIOS_PAGO_VEN_TBL VENCIMIENTOS ON VENCIMIENTOS.ID_MEDPAG_VEN = PAGOS.ID_MEDPAG_VEN
;
CREATE OR REPLACE VIEW D_PROV_PEDIDOS_CAB (
   ID_PROV_PEDIDO,
   CODEMP,
   PERIODO,
   CODSERIE,
   DESSERIE,
   NUMPED,
   FECHA,
   FECHA_SUMINISTRO_PREV,
   CODALM,
   DESALM,
   CODCAJA,
   UID_DIARIO_CAJA,
   CODAPLICACION,
   CODCONALM,
   DESCONALM,
   CODPRO,
   DESPRO,
   PERSONA_CONTACTO,
   REFERENCIA_PROVEEDOR,
   ID_GRUPO_IMPUESTOS,
   ID_TRAT_IMPUESTOS,
   DESTRATIMP,
   BASE,
   IMPUESTOS,
   TOTAL,
   OBSERVACIONES,
   ID_USUARIO,
   ESTADO,
   SUBESTADO,
   DESESTADO )
AS
SELECT PEDIDOS_CAB.ID_PROV_PEDIDO,
       PEDIDOS_CAB.CODEMP,
       PEDIDOS_CAB.PERIODO,
       PEDIDOS_CAB.CODSERIE,
       SERIES.DESSERIE,
       PEDIDOS_CAB.NUMPED,
       PEDIDOS_CAB.FECHA,
       PEDIDOS_CAB.FECHA_SUMINISTRO_PREV,
       PEDIDOS_CAB.CODALM,
       ALMACENES.DESALM,
       PEDIDOS_CAB.CODCAJA,
       PEDIDOS_CAB.UID_DIARIO_CAJA,
       PEDIDOS_CAB.CODAPLICACION,
       PEDIDOS_CAB.CODCONALM,
       ALMACENES_CONCEPTOS.DESCONALM,
       PEDIDOS_CAB.CODPRO,
       PROVEEDORES.DESPRO,
       PEDIDOS_CAB.PERSONA_CONTACTO,
       PEDIDOS_CAB.REFERENCIA_PROVEEDOR,
       PEDIDOS_CAB.ID_GRUPO_IMPUESTOS,
       PEDIDOS_CAB.ID_TRAT_IMPUESTOS,
       TRAT_IMP.DESTRATIMP,
       PEDIDOS_CAB.BASE,
       PEDIDOS_CAB.IMPUESTOS,
       PEDIDOS_CAB.TOTAL,
       PEDIDOS_CAB.OBSERVACIONES,
       PEDIDOS_CAB.ID_USUARIO,
       PEDIDOS_CAB.ESTADO,
       PEDIDOS_CAB.SUBESTADO,
       ESTADOS_EMISOR.DESESTADO
  FROM D_PROV_PEDIDOS_CAB_TBL PEDIDOS_CAB
       INNER JOIN D_SERIES_TBL SERIES ON PEDIDOS_CAB.CODSERIE = SERIES.CODSERIE
       INNER JOIN D_ALMACENES_TBL ALMACENES ON PEDIDOS_CAB.CODALM = ALMACENES.CODALM
       INNER JOIN D_ALMACENES_CONCEPTOS_TBL ALMACENES_CONCEPTOS ON (ALMACENES_CONCEPTOS.CODAPLICACION = PEDIDOS_CAB.CODAPLICACION
                                                                AND PEDIDOS_CAB.CODCONALM = ALMACENES_CONCEPTOS.CODCONALM)
       INNER JOIN D_PROVEEDORES_TBL PROVEEDORES ON PEDIDOS_CAB.CODPRO = PROVEEDORES.CODPRO
       INNER JOIN CONFIG_ESTADOS_TBL ESTADOS_EMISOR ON (ESTADOS_EMISOR.PROCESO = 'PEDPRO'
                                                    AND ESTADOS_EMISOR.ESTADO = PEDIDOS_CAB.ESTADO)
							LEFT JOIN CONFIG_IMP_TRATAMIENTO_TBL TRAT_IMP ON (PEDIDOS_CAB.ID_TRAT_IMPUESTOS = TRAT_IMP.ID_TRAT_IMPUESTOS)
;
CREATE OR REPLACE VIEW D_PROV_PEDIDOS_DET (
   ID_PROV_PEDIDO,
   LINEA,
   CODART,
   DESART,
   UNIDAD_MEDIDA_ALTERNATIVA,
   DESGLOSE1,
   DESGLOSE2,
   DESCRIPCION_AMPLIADA,
   UNIDAD_MEDIDA,
   CANTIDAD_MEDIDA_SOLICITADA,
   CANTIDAD_SOLICITADA,
   CANTIDAD_MEDIDA_ACEPTADA,
   CANTIDAD_ACEPTADA,
   CANTIDAD_MEDIDA_RECEPCIONADA,
   CANTIDAD_RECEPCIONADA,
   PRECIO,
   DESCUENTO,
   IMPORTE,
   CODIMP,
   LESTADO,
   LSUBESTADO,
   LDESESTADO )
AS
SELECT PEDIDOS_DET.ID_PROV_PEDIDO,
       PEDIDOS_DET.LINEA,
       PEDIDOS_DET.CODART,
       PEDIDOS_DET.DESART,
       ARTICULOS.UNIDAD_MEDIDA_ALTERNATIVA,
       PEDIDOS_DET.DESGLOSE1,
       PEDIDOS_DET.DESGLOSE2,
       PEDIDOS_DET.DESCRIPCION_AMPLIADA,
       PEDIDOS_DET.UNIDAD_MEDIDA,
       PEDIDOS_DET.CANTIDAD_MEDIDA_SOLICITADA,
       PEDIDOS_DET.CANTIDAD_SOLICITADA,
       PEDIDOS_DET.CANTIDAD_MEDIDA_ACEPTADA,
       PEDIDOS_DET.CANTIDAD_ACEPTADA,
       PEDIDOS_DET.CANTIDAD_MEDIDA_RECEPCIONADA,
       PEDIDOS_DET.CANTIDAD_RECEPCIONADA,
       PEDIDOS_DET.PRECIO,
       PEDIDOS_DET.DESCUENTO,
       PEDIDOS_DET.IMPORTE,
       PEDIDOS_DET.CODIMP,
       PEDIDOS_DET.LESTADO,
       PEDIDOS_DET.LSUBESTADO,
       ESTADOS.DESESTADO AS LDESESTADO
  FROM D_PROV_PEDIDOS_DET_TBL PEDIDOS_DET
       INNER JOIN D_ARTICULOS_TBL ARTICULOS ON (ARTICULOS.CODART = PEDIDOS_DET.CODART)
       LEFT JOIN CONFIG_ESTADOS_TBL ESTADOS ON (ESTADOS.PROCESO = 'PEDPRO_LINEA'
                                             AND ESTADOS.ESTADO = PEDIDOS_DET.LESTADO
                                             AND ESTADOS.SUBESTADO = PEDIDOS_DET.LSUBESTADO)
;
CREATE OR REPLACE VIEW D_PROV_PEDIDOS_PAG (
   ID_PROV_PEDIDO,
   LINEA,
   ID_MEDPAG_VEN,
   DESMEDPAG_VEN,
   IMPORTE )
AS
SELECT PAGOS.ID_PROV_PEDIDO,
       PAGOS.LINEA,
       PAGOS.ID_MEDPAG_VEN,
       VENCIMIENTOS.DESMEDPAG_VEN,
       PAGOS.IMPORTE
  FROM D_PROV_PEDIDOS_PAG_TBL PAGOS
       INNER JOIN D_MEDIOS_PAGO_VEN_TBL VENCIMIENTOS ON VENCIMIENTOS.ID_MEDPAG_VEN = PAGOS.ID_MEDPAG_VEN
;
CREATE OR REPLACE VIEW D_PROVEEDORES (
   CODPRO,
   DESPRO,
   TIPO_PROVEEDOR,
   NOMBRE_COMERCIAL,
   DOMICILIO,
   POBLACION,
   PROVINCIA,
   CP,
   CODPAIS,
   DESPAIS,
   TELEFONO1,
   TELEFONO2,
   FAX,
   PERSONA_CONTACTO,
   EMAIL,
   CIF,
   ID_TRAT_IMPUESTOS,
   CODTRATIMP,
   DESTRATIMP,
   ID_MEDPAG_VEN,
   DESMEDPAG_VEN,
   OBSERVACIONES,
   ACTIVO,
   FECHA_ALTA,
   FECHA_BAJA,
   BANCO,
   BANCO_DOMICILIO,
   BANCO_POBLACION,
   CCC )
AS
SELECT	PROVEEDORES.CODPRO, PROVEEDORES.DESPRO, PROVEEDORES.TIPO_PROVEEDOR, PROVEEDORES.NOMBRE_COMERCIAL, PROVEEDORES.DOMICILIO,
							PROVEEDORES.POBLACION, PROVEEDORES.PROVINCIA, PROVEEDORES.CP, PROVEEDORES.CODPAIS, PAISES.DESPAIS,
                            PROVEEDORES.TELEFONO1, PROVEEDORES.TELEFONO2, PROVEEDORES.FAX, PROVEEDORES.PERSONA_CONTACTO,
                            PROVEEDORES.EMAIL, PROVEEDORES.CIF, PROVEEDORES.ID_TRAT_IMPUESTOS,
							TRATIMP.CODTRATIMP, TRATIMP.DESTRATIMP,
							PROVEEDORES.ID_MEDPAG_VEN, MEDPAG_VEN.DESMEDPAG_VEN, PROVEEDORES.OBSERVACIONES, PROVEEDORES.ACTIVO,
							PROVEEDORES.FECHA_ALTA, PROVEEDORES.FECHA_BAJA, PROVEEDORES.BANCO, PROVEEDORES.BANCO_DOMICILIO,
							PROVEEDORES.BANCO_POBLACION, PROVEEDORES.CCC
		FROM D_PROVEEDORES_TBL PROVEEDORES
							LEFT JOIN D_PAISES_TBL PAISES ON (PROVEEDORES.CODPAIS = PAISES.CODPAIS)
							LEFT JOIN CONFIG_IMP_TRATAMIENTO_TBL TRATIMP ON (PROVEEDORES.ID_TRAT_IMPUESTOS = TRATIMP.ID_TRAT_IMPUESTOS)
							LEFT JOIN D_MEDIOS_PAGO_VEN_TBL MEDPAG_VEN ON (PROVEEDORES.ID_MEDPAG_VEN = MEDPAG_VEN.ID_MEDPAG_VEN)
;
CREATE OR REPLACE VIEW D_SINCRONIZADOR_TRABAJOS (
   ID_TRABAJO,
   TRABAJO,
   CLASE,
   CODALM,
   DESALM,
   ESTADO,
   FECHA_INICIO,
   INTERVALO,
   FECHA_PROXIMA_EJEC,
   FECHA_ULTIMA_EJEC,
   RESULTADO,
   OBSERVACIONES )
AS
SELECT TRABAJOS.ID_TRABAJO,
       TRABAJOS.TRABAJO,
       TRABAJOS.CLASE,
       TRABAJOS.CODALM,
       ALMACENES.DESALM,
       TRABAJOS.ESTADO,
       TRABAJOS.FECHA_INICIO,
       TRABAJOS.INTERVALO,
       TRABAJOS.FECHA_PROXIMA_EJEC,
       TRABAJOS.FECHA_ULTIMA_EJEC,
       TRABAJOS.RESULTADO,
       TRABAJOS.OBSERVACIONES
  FROM D_SINCRONIZADOR_TRABAJOS_TBL TRABAJOS,
       D_ALMACENES_TBL ALMACENES
 WHERE TRABAJOS.CODALM = ALMACENES.CODALM
;
CREATE OR REPLACE VIEW D_TARIFAS_ACT_CAB (
   CODTAR,
   DESTAR,
   VERSION,
   ID_GRUPO_IMPUESTOS,
   ID_TRAT_IMPUESTOS,
   ID_ACTUALIZACION,
   DES_ACTUALIZACION,
   FECHA_PREVISTA_APLICACION )
AS
SELECT ACTUALIZACIONES.CODTAR, TARIFAS.DESTAR, TARIFAS.VERSION, TARIFAS.ID_GRUPO_IMPUESTOS,
    TARIFAS.ID_TRAT_IMPUESTOS, ACTUALIZACIONES.ID_ACTUALIZACION,
    ACTUALIZACIONES.DES_ACTUALIZACION, ACTUALIZACIONES.FECHA_PREVISTA_APLICACION
    FROM D_TARIFAS_ACT_CAB_TBL ACTUALIZACIONES
    INNER JOIN D_TARIFAS_CAB_TBL TARIFAS ON (TARIFAS.CODTAR = ACTUALIZACIONES.CODTAR)
;
CREATE OR REPLACE VIEW D_TARIFAS_ACT_DET (
   CODTAR,
   ID_ACTUALIZACION,
   CODART,
   DESART,
   CODIMP,
   PRECIO_COSTO,
   FACTOR_MARCAJE,
   PRECIO_VENTA,
   PRECIO_TOTAL )
AS
SELECT TARIFAS.CODTAR, TARIFAS.ID_ACTUALIZACION, TARIFAS.CODART, ARTICULOS.DESART,
    ARTICULOS.CODIMP, TARIFAS.PRECIO_COSTO, TARIFAS.FACTOR_MARCAJE, TARIFAS.PRECIO_VENTA, TARIFAS.PRECIO_TOTAL
    FROM D_TARIFAS_ACT_DET_TBL TARIFAS
        INNER JOIN D_ARTICULOS_TBL ARTICULOS ON (ARTICULOS.CODART = TARIFAS.CODART)
;
CREATE OR REPLACE VIEW D_TARIFAS_CAB (
   CODTAR,
   DESTAR,
   VERSION,
   ID_GRUPO_IMPUESTOS,
   ID_TRAT_IMPUESTOS,
   DESTRATIMP,
   FECHA_VERSION )
AS
SELECT TARIFAS.CODTAR,
       TARIFAS.DESTAR,
       TARIFAS.VERSION,
       TARIFAS.ID_GRUPO_IMPUESTOS,
       TARIFAS.ID_TRAT_IMPUESTOS,
       TRATIMP.DESTRATIMP,
       TARIFAS.FECHA_VERSION
    FROM D_TARIFAS_CAB_TBL TARIFAS
        LEFT JOIN CONFIG_IMP_TRATAMIENTO_TBL TRATIMP ON (TARIFAS.ID_TRAT_IMPUESTOS = TRATIMP.ID_TRAT_IMPUESTOS)
;
CREATE OR REPLACE VIEW D_TARIFAS_DET (
   CODTAR,
   DESTAR,
   CODART,
   PRECIO_COSTO,
   FACTOR_MARCAJE,
   PRECIO_VENTA,
   PRECIO_TOTAL,
   VERSION,
   DESART,
   CODFAM,
   CODPRO,
   CODIMP )
AS
SELECT DET_TAR.CODTAR, CAB_TAR.DESTAR, DET_TAR.CODART, DET_TAR.PRECIO_COSTO, DET_TAR.FACTOR_MARCAJE,
     DET_TAR.PRECIO_VENTA, DET_TAR.PRECIO_TOTAL, DET_TAR.VERSION, ARTICULOS.DESART, ARTICULOS.CODFAM,
     ARTICULOS.CODPRO, ARTICULOS.CODIMP
        FROM D_TARIFAS_DET_TBL DET_TAR
							INNER JOIN D_ARTICULOS_TBL ARTICULOS ON (DET_TAR.CODART = ARTICULOS.CODART)
							INNER JOIN D_TARIFAS_CAB_TBL CAB_TAR ON (CAB_TAR.CODTAR = DET_TAR.CODTAR)
;
CREATE OR REPLACE VIEW D_TICKETS (
   UID_TICKET,
   CODALM,
   DESALM,
   ID_TICKET,
   FECHA,
   TICKET,
   CODEMP )
AS
SELECT UID_TICKET, TICKET.CODALM, ALMACEN.DESALM, TICKET.ID_TICKET, TICKET.FECHA, TICKET.TICKET, ALMACEN.CODEMP
	 FROM D_TICKETS_TBL TICKET,
	      D_ALMACENES_TBL ALMACEN
	 WHERE (TICKET.CODALM = ALMACEN.CODALM)
;
CREATE OR REPLACE VIEW D_TICKETS_ERR (
   UID_TICKET,
   CODALM,
   DESALM,
   FECHA,
   ID_TICKET,
   FECHA_PROCESO,
   MENSAJE_ERROR,
   TICKET )
AS
SELECT TICKET.UID_TICKET, TICKET.CODALM, ALMACEN.DESALM, TICKET.FECHA, TICKET.ID_TICKET, TICKET.FECHA_PROCESO,
				   TICKET.MENSAJE_ERROR, TICKET.TICKET
	 FROM D_TICKETS_ERR_TBL TICKET,
	      D_ALMACENES_TBL ALMACEN
	 WHERE (TICKET.CODALM = ALMACEN.CODALM)
;
CREATE OR REPLACE VIEW D_TICKETS_HIST (
   UID_TICKET,
   CODALM,
   DESALM,
   ID_TICKET,
   FECHA,
   TICKET )
AS
SELECT TICKET.UID_TICKET, TICKET.CODALM, ALMACEN.DESALM, TICKET.ID_TICKET, TICKET.FECHA, TICKET.TICKET
	 FROM D_TICKETS_HIST_TBL TICKET,
	      D_ALMACENES_TBL ALMACEN
	 WHERE (TICKET.CODALM = ALMACEN.CODALM)
;
CREATE OR REPLACE VIEW D_TIENDAS (
   CODALM,
   DESALM,
   DOMICILIO,
   POBLACION,
   PROVINCIA,
   CP,
   TELEFONO1,
   TELEFONO2,
   FAX,
   PERSONA_CONTACTO,
   CODEMP,
   CODCLI,
   DESCLI,
   ID_TIPO_TIENDA,
   ACTIVO,
   VERSION_ARTICULOS,
   VERSION_ARTICULOS_REV,
   FECHA_VERSION_ARTICULOS,
   FECHA_VERSION_ARTICULOS_REV,
   CONFIGURACION,
   DESTIPO_TIENDA,
   CLASE_CONFIGURACION,
   CLASE_SINCRONIZACION,
   CODMEDPAG_POR_DEFECTO,
   DESMEDPAG,
   CODCONALM_VENTAS,
   DESCONALM )
AS
SELECT  ALMACENES.CODALM, ALMACENES.DESALM, ALMACENES.DOMICILIO, ALMACENES.POBLACION, ALMACENES.PROVINCIA,
        ALMACENES.CP, ALMACENES.TELEFONO1, ALMACENES.TELEFONO2, ALMACENES.FAX, ALMACENES.PERSONA_CONTACTO,
        ALMACENES.CODEMP, ALMACENES.CODCLI, CLIENTES.DESCLI, TIENDAS.ID_TIPO_TIENDA, TIENDAS.ACTIVO,
        TIENDAS.VERSION_ARTICULOS, TIENDAS.VERSION_ARTICULOS_REV, TIENDAS.FECHA_VERSION_ARTICULOS,
        TIENDAS.FECHA_VERSION_ARTICULOS_REV, TIENDAS.CONFIGURACION, TIENDAS_TIPOS.DESTIPO_TIENDA,
        TIENDAS_TIPOS.CLASE_CONFIGURACION, TIENDAS_TIPOS.CLASE_SINCRONIZACION,
        TIENDAS.CODMEDPAG_POR_DEFECTO, MEDIOSPAGO.DESMEDPAG,
        TIENDAS.CODCONALM_VENTAS, CONALM.DESCONALM
FROM D_TIENDAS_TBL TIENDAS
        INNER JOIN D_ALMACENES_TBL ALMACENES ON (ALMACENES.CODALM = TIENDAS.CODALM)
        INNER JOIN D_CLIENTES_TBL CLIENTES ON (CLIENTES.CODCLI = ALMACENES.CODCLI)
        INNER JOIN CONFIG_TIENDAS_TIPOS_TBL TIENDAS_TIPOS ON (TIENDAS_TIPOS.ID_TIPO_TIENDA = TIENDAS.ID_TIPO_TIENDA)
        INNER JOIN D_MEDIOS_PAGO_TBL MEDIOSPAGO ON (MEDIOSPAGO.CODMEDPAG = TIENDAS.CODMEDPAG_POR_DEFECTO)
        INNER JOIN D_ALMACENES_CONCEPTOS_TBL CONALM ON (CONALM.CODAPLICACION = 'VENT' AND CONALM.CODCONALM = TIENDAS.CODCONALM_VENTAS)
;
CREATE OR REPLACE VIEW D_TIENDAS_TARIFAS (
   CODALM,
   CODTAR,
   DESTAR,
   VERSION_TARIFA,
   FECHA_VERSION_TARIFA,
   VERSION_TARIFA_REV,
   FECHA_VERSION_TARIFA_REV )
AS
SELECT TIEND_TAR.CODALM, TIEND_TAR.CODTAR, TARIFAS.DESTAR, TIEND_TAR.VERSION_TARIFA,
       TIEND_TAR.FECHA_VERSION_TARIFA, TIEND_TAR.VERSION_TARIFA_REV, TIEND_TAR.FECHA_VERSION_TARIFA_REV
            FROM D_TIENDAS_TARIFAS_TBL TIEND_TAR
							INNER JOIN D_TARIFAS_CAB_TBL TARIFAS ON (TIEND_TAR.CODTAR = TARIFAS.CODTAR)
;
CREATE OR REPLACE VIEW D_TIENDAS_USUARIOS (
   ID_USUARIO,
   CODALM,
   DESALM,
   VERSION_ARTICULOS,
   FECHA_VERSION_ARTICULOS,
   VERSION_ARTICULOS_REV,
   FECHA_VERSION_ARTICULOS_REV )
AS
SELECT alm.id_usuario, t.codalm, a.desalm, t.version_articulos, t.fecha_version_articulos, t.version_articulos_rev,
    t.fecha_version_articulos_rev
    FROM D_TIENDAS_TBL t
    INNER JOIN D_ALMACENES_USUARIOS_TBL alm ON (t.codalm = alm.codalm)
    INNER JOIN D_ALMACENES a ON (t.codalm = a.codalm)
;
CREATE OR REPLACE VIEW D_TIPOS_PORTES (
   ID_TIPO_PORTE,
   DESTIPOPORTE,
   CODART_PORTE,
   DESART_PORTE,
   DESDE_VOLUMEN_VENTA,
   URL_TRACKING )
AS
SELECT	TIPOSPORTES.ID_TIPO_PORTE, TIPOSPORTES.DESTIPOPORTE, TIPOSPORTES.CODART_PORTE,
        ARTICULOS.DESART AS DESART_PORTE, TIPOSPORTES.DESDE_VOLUMEN_VENTA, TIPOSPORTES.URL_TRACKING
FROM D_TIPOS_PORTES_TBL TIPOSPORTES
        LEFT JOIN D_ARTICULOS_TBL ARTICULOS ON (TIPOSPORTES.CODART_PORTE = ARTICULOS.CODART)
;
CREATE OR REPLACE VIEW T_ARTICULOS (
   CODART,
   DESART,
   CODCAT,
   CODALM,
   ACTIVO,
   OBSERVACIONES,
   ESCAPARATE,
   FECHA_ALTA,
   STOCK,
   STOCK_PENDIENTE_RECIBIR,
   DESGLOSE1,
   DESGLOSE2,
   CODALM_CENTRAL,
   CODIMP )
AS
SELECT  ARTICULOS.CODART, ARTICULOS.DESART, ARTICULOS.CODCAT, ARTICULOS.CODALM,
        ARTICULOS.ACTIVO, ARTICULOS.OBSERVACIONES, ARTICULOS.ESCAPARATE,
        ARTICULOS.FECHA_ALTA, ALMACENES.STOCK, ALMACENES.STOCK_PENDIENTE_RECIBIR,
        ALMACENES.DESGLOSE1, ALMACENES.DESGLOSE2, ALMACENES.CODALM CODALM_CENTRAL, ARTICULOS.CODIMP
FROM T_ARTICULOS_TBL ARTICULOS
        LEFT JOIN D_ALMACENES_ARTICULOS_TBL ALMACENES ON (ALMACENES.CODART = ARTICULOS.CODART)
;
CREATE OR REPLACE VIEW T_CATEGORIZACION (
   CODCAT,
   DESCAT,
   CODCAT_PADRE,
   ACTIVO,
   CODALM )
AS
SELECT CODCAT, DESCAT, SUBSTR(CODCAT, 1, 2) CODCAT_PADRE, ACTIVO, CODALM
    FROM T_CATEGORIZACION_TBL
        WHERE  LENGTH(CODCAT) <= 4
            ORDER BY CODCAT
;
CREATE OR REPLACE VIEW T_CLIENTES (
   CODALM,
   CIF,
   DESCLI,
   NOMBRE_COMERCIAL,
   DOMICILIO,
   POBLACION,
   PROVINCIA,
   CP,
   TELEFONO1,
   TELEFONO2,
   FAX,
   PERSONA_CONTACTO,
   EMAIL,
   ID_TRAT_IMPUESTOS,
   CODMEDPAG,
   CODTAR,
   OBSERVACIONES,
   ACTIVO,
   FECHA_ALTA,
   FECHA_BAJA,
   VENTA_A_CREDITO,
   USUARIO,
   CLAVE )
AS
SELECT CLIENTES.CODALM, CLIENTES.CIF, CLIENTES.DESCLI, CLIENTES.NOMBRE_COMERCIAL,
        CLIENTES.DOMICILIO, CLIENTES.POBLACION, CLIENTES.PROVINCIA, CLIENTES.CP,
        CLIENTES.TELEFONO1, CLIENTES.TELEFONO2, CLIENTES.FAX, CLIENTES.PERSONA_CONTACTO,
        CLIENTES.EMAIL, CLIENTES.ID_TRAT_IMPUESTOS, CLIENTES.CODMEDPAG, CLIENTES.CODTAR,
        CLIENTES.OBSERVACIONES, CLIENTES.ACTIVO, CLIENTES.FECHA_ALTA, CLIENTES.FECHA_BAJA,
        CLIENTES.VENTA_A_CREDITO, CLIENTES_TV.USUARIO, CLIENTES_TV.CLAVE
FROM T_CLIENTES_TBL CLIENTES
        LEFT JOIN TV_CLIENTES_TBL CLIENTES_TV ON (CLIENTES_TV.CODALM = CLIENTES.CODALM AND CLIENTES_TV.CIF = CLIENTES.CIF)
;
CREATE OR REPLACE VIEW T_TIENDAS_CAJAS (
   CODALM,
   UID_TPV,
   CONFIGURACION,
   CLIENTE_POR_DEFECTO )
AS
SELECT TIENDAS_CAJAS.CODALM, TIENDAS_CAJAS.UID_TPV, TIENDAS_CAJAS.CONFIGURACION,
        TIENDAS.CLIENTE_POR_DEFECTO
FROM T_TIENDAS_CAJAS_TBL TIENDAS_CAJAS
        LEFT JOIN T_TIENDAS_TBL TIENDAS ON (TIENDAS.CODALM = TIENDAS_CAJAS.CODALM)
;