-- ------------------------------------------------------------
-- Copyright 2009-2014 RED.ES - Desarrollado por TIER1
-- 
-- Licencia con arreglo a la EUPL, versión 1.1 o -en cuanto 
-- sean aprobadas por la comisión Europea- versiones 
-- posteriores de la EUPL (la "Licencia").
-- Solo podrá usarse esta obra si se respeta la Licencia.
-- 
-- http://ec.europa.eu/idabc/eupl.html
-- 
-- Salvo cuando lo exija la legislación aplicable o se acuerde
-- por escrito, el programa distribuido con arreglo a la
-- Licencia se distribuye "TAL CUAL",
-- SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, 
-- ni expresas ni implícitas.
-- Véase la Licencia en el idioma concreto que rige
-- los permisos y limitaciones que establece la Licencia.
-- ------------------------------------------------------------

CREATE TABLE CONFIG_ACCIONES_INFORMES_TBL
    (ID_ACCION                      NUMBER(10,0) NOT NULL,
    ID_VERSION                     NUMBER(10,0) NOT NULL,
    VERSION                        VARCHAR2(50) NOT NULL,
    DESCRIPCION                    VARCHAR2(250),
    FORMATO_SALIDA                 VARCHAR2(30),
    ACTIVO                         CHAR(1) NOT NULL,
    TITULO                         VARCHAR2(50))
;
ALTER TABLE CONFIG_ACCIONES_INFORMES_TBL
ADD CONSTRAINT CONFIG_ACCIONES_INFORMES_PK PRIMARY KEY (ID_ACCION, ID_VERSION)
USING INDEX
;

CREATE TABLE CONFIG_ACCIONES_OPERACIONE_TBL
    (ID_ACCION                      NUMBER(10,0) NOT NULL,
    ID_OPERACION                   NUMBER(2,0) NOT NULL,
    ORDEN                          NUMBER(2,0) NOT NULL,
    DESOPERACION                   VARCHAR2(30) NOT NULL)
;
ALTER TABLE CONFIG_ACCIONES_OPERACIONE_TBL
ADD CONSTRAINT CONFIG_ACCIONES_OPERACIONE_PK PRIMARY KEY (ID_ACCION, 
  ID_OPERACION)
USING INDEX
;

CREATE TABLE CONFIG_ACCIONES_PERMISOS_TBL
    (ID_ACCION                      NUMBER(10,0) NOT NULL,
    ID_OPERACION                   NUMBER(2,0) NOT NULL,
    ID_USUARIO                     NUMBER(10,0) NOT NULL,
    ID_PERFIL                      NUMBER(10,0) NOT NULL,
    ACCESO                         NUMBER(1,0) NOT NULL)
;
ALTER TABLE CONFIG_ACCIONES_PERMISOS_TBL
ADD CONSTRAINT CONFIG_ACCIONES_PERMISOS_PK PRIMARY KEY (ID_ACCION, ID_OPERACION, 
  ID_USUARIO, ID_PERFIL)
USING INDEX
;

CREATE TABLE CONFIG_ACCIONES_TBL
    (ID_ACCION                      NUMBER(10,0) NOT NULL,
    ACCION                         VARCHAR2(250),
    TIPO_ACCION                    VARCHAR2(10) NOT NULL,
    EJECUCION                      VARCHAR2(250) NOT NULL,
    PARAMETROS                     VARCHAR2(250),
    DESCRIPCION                    VARCHAR2(250),
    TITULO                         VARCHAR2(250),
    ICONO                          VARCHAR2(250),
    ACTIVO                         CHAR(1) NOT NULL)
;
ALTER TABLE CONFIG_ACCIONES_TBL
ADD CONSTRAINT CONFIG_ACCIONES_PK PRIMARY KEY (ID_ACCION)
USING INDEX
;

ALTER TABLE CONFIG_ACCIONES_TBL
ADD CONSTRAINT CONFIG_ACCIONES_UK UNIQUE (ACCION)
USING INDEX
;

CREATE TABLE CONFIG_AYUDAS_TBL
    (NOMBRE                         VARCHAR2(50) NOT NULL,
    DEFINICION                     BLOB NOT NULL)
;
CREATE TABLE CONFIG_CONTADORES_DEF_TBL
    (ID_CONTADOR                    VARCHAR2(20) NOT NULL,
    USA_CODEMP                     CHAR(1) NOT NULL,
    USA_CODSERIE                   CHAR(1) NOT NULL,
    USA_PERIODO                    CHAR(1) NOT NULL,
    DESCRIPCION                    VARCHAR2(30))
;
ALTER TABLE CONFIG_CONTADORES_DEF_TBL
ADD CONSTRAINT CONFIG_CONTADORES_DEF_PK PRIMARY KEY (ID_CONTADOR)
USING INDEX
;

CREATE TABLE CONFIG_CONTADORES_TBL
    (ID_CONTADOR                    VARCHAR2(20) NOT NULL,
    CODEMP                         VARCHAR2(4) NOT NULL,
    CODSERIE                       VARCHAR2(5) NOT NULL,
    PERIODO                        NUMBER(4,0) NOT NULL,
    VALOR                          NUMBER(10,0) NOT NULL)
;
ALTER TABLE CONFIG_CONTADORES_TBL
ADD CONSTRAINT CONFIG_CONTADORES_PK PRIMARY KEY (ID_CONTADOR, CODEMP, CODSERIE, 
  PERIODO)
USING INDEX
;

CREATE TABLE CONFIG_ESTADOS_TBL
    (PROCESO                        VARCHAR2(30) NOT NULL,
    ESTADO                         NUMBER(3,0) NOT NULL,
    SUBESTADO                      NUMBER(3,0) NOT NULL,
    DESESTADO                      VARCHAR2(50) NOT NULL,
    ABREVIATURA                    VARCHAR2(30),
    ICONO                          VARCHAR2(250),
    AMBITO_APLICACION              VARCHAR2(250))
;
ALTER TABLE CONFIG_ESTADOS_TBL
ADD CONSTRAINT CONFIG_ESTADOS_PK PRIMARY KEY (PROCESO, ESTADO, SUBESTADO)
USING INDEX
;

CREATE TABLE CONFIG_IMP_GRUPOS_TBL
    (ID_GRUPO_IMPUESTOS             NUMBER(5,0) NOT NULL,
    VIGENCIA_DESDE                 DATE NOT NULL)
;
ALTER TABLE CONFIG_IMP_GRUPOS_TBL
ADD CONSTRAINT CONFIG_IMP_GRUPOS_PK PRIMARY KEY (ID_GRUPO_IMPUESTOS)
USING INDEX
;

CREATE TABLE CONFIG_IMP_PORCENTAJES_TBL
    (ID_GRUPO_IMPUESTOS             NUMBER(5,0) NOT NULL,
    ID_TRAT_IMPUESTOS              NUMBER(10,0) NOT NULL,
    CODIMP                         CHAR(1) NOT NULL,
    PORCENTAJE                     NUMBER(13,3) NOT NULL,
    PORCENTAJE_RECARGO             NUMBER(13,3) NOT NULL)
;
ALTER TABLE CONFIG_IMP_PORCENTAJES_TBL
ADD CONSTRAINT CONFIG_IMP_PORCENTAJES_PK PRIMARY KEY (ID_GRUPO_IMPUESTOS, 
  ID_TRAT_IMPUESTOS, CODIMP)
USING INDEX
;

CREATE TABLE CONFIG_IMP_TIPOS_TBL
    (CODIMP                         CHAR(1) NOT NULL,
    DESIMP                         VARCHAR2(45) NOT NULL)
;
ALTER TABLE CONFIG_IMP_TIPOS_TBL
ADD CONSTRAINT CONFIG_IMP_TIPOS_PK PRIMARY KEY (CODIMP)
USING INDEX
;

CREATE TABLE CONFIG_IMP_TRATAMIENTO_TBL
    (ID_TRAT_IMPUESTOS              NUMBER(10,0) NOT NULL,
    CODTRATIMP                     VARCHAR2(11) NOT NULL,
    DESTRATIMP                     VARCHAR2(45) NOT NULL,
    APLICA_RECARGO                 CHAR(1) NOT NULL)
;
ALTER TABLE CONFIG_IMP_TRATAMIENTO_TBL
ADD CONSTRAINT CONFIG_IMP_TRATAMIENTO_PK PRIMARY KEY (ID_TRAT_IMPUESTOS)
USING INDEX
;

ALTER TABLE CONFIG_IMP_TRATAMIENTO_TBL
ADD CONSTRAINT CONFIG_IMP_TRATAMIENTO_UK UNIQUE (CODTRATIMP)
USING INDEX
;

CREATE TABLE CONFIG_MENU_TBL
    (APLICACION                     VARCHAR2(30) NOT NULL,
    ORDEN                          NUMBER(4,0) NOT NULL,
    OPCION                         VARCHAR2(250),
    ID_ACCION                      NUMBER(10,0),
    TECLA_RAPIDA                   VARCHAR2(10))
;
ALTER TABLE CONFIG_MENU_TBL
ADD CONSTRAINT CONFIG_MENU_PK PRIMARY KEY (APLICACION, ORDEN)
USING INDEX
;

CREATE TABLE CONFIG_PERFILES_TBL
    (ID_PERFIL                      NUMBER(10,0) NOT NULL,
    DESPERFIL                      VARCHAR2(30))
;
ALTER TABLE CONFIG_PERFILES_TBL
ADD CONSTRAINT CONFIG_PERFILES_PK PRIMARY KEY (ID_PERFIL)
USING INDEX
;

CREATE TABLE CONFIG_TIENDAS_TIPOS_TBL
    (ID_TIPO_TIENDA                 NUMBER(10,0) NOT NULL,
    DESTIPO_TIENDA                 VARCHAR2(45) NOT NULL,
    CLASE_CONFIGURACION            VARCHAR2(255) NOT NULL,
    CLASE_SINCRONIZACION           VARCHAR2(255) NOT NULL)
;
ALTER TABLE CONFIG_TIENDAS_TIPOS_TBL
ADD CONSTRAINT CONFIG_TIENDAS_TIPOS_PK PRIMARY KEY (ID_TIPO_TIENDA)
USING INDEX
;

CREATE TABLE CONFIG_TIENDAS_TIPOS_TRAB_TBL
    (ID_TIPO_TIENDA                 NUMBER(10,0) NOT NULL,
    TRABAJO                        VARCHAR2(45) NOT NULL,
    CLASE                          VARCHAR2(255) NOT NULL,
    INTERVALO                      VARCHAR2(45))
;

ALTER TABLE CONFIG_TIENDAS_TIPOS_TRAB_TBL
ADD CONSTRAINT CONFIG_TIENDAS_TIPOS_TRAB_PK PRIMARY KEY (ID_TIPO_TIENDA, TRABAJO)
USING INDEX
;

CREATE TABLE CONFIG_USUARIOS_PERFILES_TBL
    (ID_USUARIO                     NUMBER(10,0) NOT NULL,
    ID_PERFIL                      NUMBER(10,0) NOT NULL)
;


ALTER TABLE CONFIG_USUARIOS_PERFILES_TBL
ADD CONSTRAINT CONFIG_USUARIOS_PERFILES_PK PRIMARY KEY (ID_USUARIO, ID_PERFIL)
USING INDEX
;

CREATE TABLE CONFIG_USUARIOS_TBL
    (ID_USUARIO                     NUMBER(10,0) NOT NULL,
    USUARIO                        VARCHAR2(20) NOT NULL,
    DESUSUARIO                     VARCHAR2(50),
    CLAVE                          VARCHAR2(250),
    ACTIVO                         CHAR(1) NOT NULL,
    APLICACION_POR_DEFECTO         VARCHAR2(30),
    PUEDE_CAMBIAR_APLICACION       CHAR(1) NOT NULL)
;
ALTER TABLE CONFIG_USUARIOS_TBL
ADD CONSTRAINT CONFIG_USUARIOS_IDU_UNQ UNIQUE (USUARIO)
USING INDEX
;

ALTER TABLE CONFIG_USUARIOS_TBL
ADD CONSTRAINT CONFIG_USUARIOS_PK PRIMARY KEY (ID_USUARIO)
USING INDEX
;

CREATE TABLE CONFIG_VARIABLES_DEF_TBL
    (ID_VARIABLE                    VARCHAR2(50) NOT NULL,
    DESCRIPCION                    VARCHAR2(255) NOT NULL,
    VALOR_DEFECTO                  VARCHAR2(250),
    NIVEL_USUARIO                  VARCHAR2(1) NOT NULL,
    NIVEL_GRUPO                    VARCHAR2(1) NOT NULL,
    NIVEL_EMPRESA                  VARCHAR2(1) NOT NULL,
    NIVEL_GENERAL                  VARCHAR2(1) NOT NULL)
;
ALTER TABLE CONFIG_VARIABLES_DEF_TBL
ADD CONSTRAINT CONFIG_VARIABLES_DEF_PK PRIMARY KEY (ID_VARIABLE)
USING INDEX
;

CREATE TABLE CONFIG_VARIABLES_TBL
    (ID_VARIABLE                    VARCHAR2(50) NOT NULL,
    PESO                           NUMBER(3,0) NOT NULL,
    ID_USUARIO                     NUMBER(10,0),
    ID_GRUPO                       NUMBER(10,0),
    CODEMP                         VARCHAR2(4),
    VALOR                          VARCHAR2(250))
;
ALTER TABLE CONFIG_VARIABLES_TBL
ADD CONSTRAINT CONFIG_VARIABLES_PK PRIMARY KEY (ID_VARIABLE, PESO)
USING INDEX
;




CREATE TABLE T_ARTICULOS_CODBAR_TBL
    (CODALM                         VARCHAR2(4) NOT NULL,
    CODART                         VARCHAR2(13) NOT NULL,
    DESGLOSE1                      VARCHAR2(15) NOT NULL,
    DESGLOSE2                      VARCHAR2(15) NOT NULL,
    CODIGO_BARRAS                  VARCHAR2(20) NOT NULL,
    DUN14                          CHAR(1) NOT NULL,
    FECHA_ALTA                     DATE NOT NULL,
    FACTOR_CONVERSION              NUMBER(13,3))
;
ALTER TABLE T_ARTICULOS_CODBAR_TBL
ADD CONSTRAINT T_ARTICULOS_CODBAR_PK PRIMARY KEY (CODALM, CODART, CODIGO_BARRAS)
USING INDEX
;

ALTER TABLE T_ARTICULOS_CODBAR_TBL
ADD CONSTRAINT T_ARTICULOS_CODBAR_UK UNIQUE (CODALM, CODIGO_BARRAS)
USING INDEX
;

CREATE TABLE T_ARTICULOS_TBL
    (CODALM                         VARCHAR2(4) NOT NULL,
    CODART                         VARCHAR2(13) NOT NULL,
    DESART                         VARCHAR2(45) NOT NULL,
    FORMATO                        VARCHAR2(20),
    CODIMP                         CHAR(1) NOT NULL,
    OBSERVACIONES                  VARCHAR2(255),
    ACTIVO                         CHAR(1),
    NUMEROS_SERIE                  CHAR(1),
    DESGLOSE1                      CHAR(1),
    DESGLOSE2                      CHAR(1),
    GENERICO                       CHAR(1) NOT NULL,
    VERSION                        NUMBER(10,0),
    UNIDADES_CAJA                  NUMBER(5,0),
    CODCAT                         VARCHAR2(20),
    ESCAPARATE                     CHAR(1),
    FECHA_ALTA                     DATE)
;
ALTER TABLE T_ARTICULOS_TBL
ADD CONSTRAINT T_ARTICULOS_PK PRIMARY KEY (CODALM, CODART)
USING INDEX
;

CREATE TABLE T_CAJA_CAB_TBL
    (UID_DIARIO_CAJA                VARCHAR2(40) NOT NULL,
    CODALM                         VARCHAR2(4) NOT NULL,
    CODCAJA                        VARCHAR2(2) NOT NULL,
    FECHA_APERTURA                 DATE NOT NULL,
    FECHA_CIERRE                   DATE,
    ID_USUARIO                     NUMBER(10,0),
    SALDO_INICIAL                  NUMBER(13,3))
;
ALTER TABLE T_CAJA_CAB_TBL
ADD CONSTRAINT T_CAJA_CAB_PK PRIMARY KEY (UID_DIARIO_CAJA)
USING INDEX
;

CREATE TABLE T_CAJA_DET_CIERRE_TBL
    (UID_DIARIO_CAJA                VARCHAR2(40) NOT NULL,
    CODMEDPAG                      VARCHAR2(4) NOT NULL,
    TOTAL                          NUMBER(13,3) NOT NULL,
    DECLARADO                      NUMBER(13,3) NOT NULL)
;
ALTER TABLE T_CAJA_DET_CIERRE_TBL
ADD CONSTRAINT T_CAJA_DET_CIERRE_PK PRIMARY KEY (UID_DIARIO_CAJA, CODMEDPAG)
USING INDEX
;

CREATE TABLE T_CAJA_DET_RECUENTO_TBL
    (UID_DIARIO_CAJA                VARCHAR2(40) NOT NULL,
    LINEA                          NUMBER(5,0) NOT NULL,
    CODMEDPAG                      VARCHAR2(4) NOT NULL,
    CANTIDAD                       NUMBER(5,0) NOT NULL,
    VALOR                          NUMBER(13,3) NOT NULL)
;
ALTER TABLE T_CAJA_DET_RECUENTO_TBL
ADD CONSTRAINT T_CAJA_DET_RECUENTO_PK PRIMARY KEY (UID_DIARIO_CAJA, LINEA)
USING INDEX
;

CREATE TABLE T_CAJA_DET_TBL
    (UID_DIARIO_CAJA                VARCHAR2(40) NOT NULL,
    LINEA                          NUMBER(5,0) NOT NULL,
    FECHA                          DATE NOT NULL,
    ENTRADA                        NUMBER(13,3),
    SALIDA                         NUMBER(13,3),
    CONCEPTO                       VARCHAR2(40) NOT NULL,
    DOCUMENTO                      VARCHAR2(10),
    CODMEDPAG                      VARCHAR2(4),
    UID_TICKET                     VARCHAR2(40))
;
ALTER TABLE T_CAJA_DET_TBL
ADD CONSTRAINT T_CAJA_DET_PK PRIMARY KEY (UID_DIARIO_CAJA, LINEA)
USING INDEX
;

CREATE TABLE T_CATEGORIZACION_TBL
    (CODALM                         VARCHAR2(4) NOT NULL,
    CODCAT                         VARCHAR2(20) NOT NULL,
    DESCAT                         VARCHAR2(45) NOT NULL,
    ACTIVO                         CHAR(1))
;
ALTER TABLE T_CATEGORIZACION_TBL
ADD CONSTRAINT T_CATEGORIZACION_PK PRIMARY KEY (CODALM, CODCAT)
USING INDEX
;

CREATE TABLE T_CLIENTES_TBL
    (CODALM                         VARCHAR2(4) NOT NULL,
    CIF                            VARCHAR2(20) NOT NULL,
    DESCLI                         VARCHAR2(45) NOT NULL,
    NOMBRE_COMERCIAL               VARCHAR2(45),
    DOMICILIO                      VARCHAR2(50),
    POBLACION                      VARCHAR2(50),
    PROVINCIA                      VARCHAR2(50),
    CP                             VARCHAR2(8),
    TELEFONO1                      VARCHAR2(15),
    TELEFONO2                      VARCHAR2(15),
    FAX                            VARCHAR2(15),
    PERSONA_CONTACTO               VARCHAR2(45),
    EMAIL                          VARCHAR2(60),
    ID_TRAT_IMPUESTOS              NUMBER(10,0) NOT NULL,
    CODMEDPAG                      VARCHAR2(4),
    CODTAR                         VARCHAR2(11),
    OBSERVACIONES                  VARCHAR2(255),
    ACTIVO                         CHAR(1) NOT NULL,
    FECHA_ALTA                     DATE,
    FECHA_BAJA                     DATE,
    VENTA_A_CREDITO                CHAR(1) NOT NULL)
;
ALTER TABLE T_CLIENTES_TBL
ADD CONSTRAINT T_CLIENTES_PK PRIMARY KEY (CODALM, CIF)
USING INDEX
;

CREATE TABLE T_CODIGOS_BARRA_ESP_TBL
    (ORDEN                          NUMBER(5,0) NOT NULL,
    DESCRIPCION                    VARCHAR2(45) NOT NULL,
    PREFIJO                        VARCHAR2(13) NOT NULL,
    CODART                         VARCHAR2(20),
    PRECIO                         VARCHAR2(20),
    CANTIDAD                       VARCHAR2(20),
    FIDELIZACION                   CHAR(1))
;
ALTER TABLE T_CODIGOS_BARRA_ESP_TBL
ADD CONSTRAINT T_CODIGOS_BARRA_ESP_PK PRIMARY KEY (ORDEN)
USING INDEX
;

CREATE TABLE T_MEDIOS_PAGO_TBL
    (CODALM                         VARCHAR2(4) NOT NULL,
    CODMEDPAG                      VARCHAR2(4) NOT NULL,
    DESMEDPAG                      VARCHAR2(45) NOT NULL,
    CONTADO                        CHAR(1),
    EFECTIVO                       CHAR(1),
    TARJETA_CREDITO                CHAR(1),
    ACTIVO                         CHAR(1) NOT NULL)
;
ALTER TABLE T_MEDIOS_PAGO_TBL
ADD CONSTRAINT T_MEDIOS_PAGO_PK PRIMARY KEY (CODALM, CODMEDPAG)
USING INDEX
;

CREATE TABLE T_PROMOCIONES_DET_TBL
    (CODALM                         VARCHAR2(4) NOT NULL,
    ID_PROMOCION                   NUMBER(10,0) NOT NULL,
    CODTAR                         VARCHAR2(11) NOT NULL,
    CODART                         VARCHAR2(13) NOT NULL,
    PRECIO_TARIFA                  NUMBER(14,4) NOT NULL,
    PRECIO_VENTA                   NUMBER(14,4),
    PUNTOS                         NUMBER(5,0) NOT NULL,
    TEXTO_PROMOCION                VARCHAR2(255),
    DATOS_PROMOCION                BLOB,
    FECHA_INICIO                   DATE NOT NULL,
    FECHA_FIN                      DATE NOT NULL,
    SOLO_FIDELIZACION              CHAR(1) NOT NULL,
    VERSION_TARIFA                 NUMBER(10,0),
    ID_TIPO_PROMOCION              NUMBER(10,0))
;
ALTER TABLE T_PROMOCIONES_DET_TBL
ADD CONSTRAINT T_PROMOCIONES_DET_PK PRIMARY KEY (CODALM, ID_PROMOCION, CODART)
USING INDEX
;

CREATE TABLE T_TARIFAS_DET_TBL
    (CODALM                         VARCHAR2(4) NOT NULL,
    CODTAR                         VARCHAR2(11) NOT NULL,
    CODART                         VARCHAR2(13) NOT NULL,
    PRECIO_COSTO                   NUMBER(14,4),
    FACTOR_MARCAJE                 NUMBER(8,4),
    PRECIO_VENTA                   NUMBER(14,4) NOT NULL,
    PRECIO_TOTAL                   NUMBER(14,4) NOT NULL,
    VERSION                        NUMBER(10,0))
;
ALTER TABLE T_TARIFAS_DET_TBL
ADD CONSTRAINT T_TARIFAS_DET_PK PRIMARY KEY (CODALM, CODTAR, CODART)
USING INDEX
;

CREATE TABLE T_TICKETS_TBL
    (UID_TICKET                     VARCHAR2(40) NOT NULL,
    CODALM                         VARCHAR2(4) NOT NULL,
    ID_TICKET                      NUMBER(10,0) NOT NULL,
    FECHA                          DATE NOT NULL,
    TICKET                         BLOB NOT NULL,
    ENVIADO                        CHAR(1) NOT NULL,
    FECHA_ENVIO                    DATE)
;
CREATE INDEX T_TICKETS_IND1 ON T_TICKETS_TBL
  (
    CODALM                          ASC,
    ENVIADO                         ASC
  )
;


ALTER TABLE T_TICKETS_TBL
ADD CONSTRAINT T_TICKETS_PK PRIMARY KEY (UID_TICKET)
USING INDEX
;

CREATE TABLE T_TIENDAS_CAJAS_TBL
    (CODALM                         VARCHAR2(4),
    CODCAJA                        VARCHAR2(2),
    UID_TPV                        VARCHAR2(40) NOT NULL,
    CONFIGURACION                  BLOB)
;
ALTER TABLE T_TIENDAS_CAJAS_TBL
ADD CONSTRAINT T_TIENDAS_CAJAS_PK PRIMARY KEY (UID_TPV)
USING INDEX
;

ALTER TABLE T_TIENDAS_CAJAS_TBL
ADD CONSTRAINT T_TIENDAS_CAJAS_UK UNIQUE (CODALM, CODCAJA)
USING INDEX
;

CREATE TABLE T_TIENDAS_TBL
    (CODALM                         VARCHAR2(4) NOT NULL,
    DESALM                         VARCHAR2(45) NOT NULL,
    NOMBRE_COMERCIAL               VARCHAR2(45),
    DOMICILIO                      VARCHAR2(50),
    POBLACION                      VARCHAR2(50),
    PROVINCIA                      VARCHAR2(50),
    CP                             VARCHAR2(8),
    TELEFONO1                      VARCHAR2(15),
    TELEFONO2                      VARCHAR2(15),
    FAX                            VARCHAR2(15),
    CIF                            VARCHAR2(20) NOT NULL,
    PERSONA_CONTACTO               VARCHAR2(45),
    ACTIVO                         CHAR(1) NOT NULL,
    CLIENTE_POR_DEFECTO            VARCHAR2(20) NOT NULL)
;
ALTER TABLE T_TIENDAS_TBL
ADD CONSTRAINT T_TIENDAS_PK PRIMARY KEY (CODALM)
USING INDEX
;

CREATE TABLE TV_CLIENTES_TBL
    (CODALM                         VARCHAR2(4) NOT NULL,
    CIF                            VARCHAR2(20) NOT NULL,
    USUARIO                        VARCHAR2(20) NOT NULL,
    CLAVE                          VARCHAR2(250) NOT NULL)
;
ALTER TABLE TV_CLIENTES_TBL
ADD CONSTRAINT TV_CLIENTES_PK PRIMARY KEY (CODALM, CIF)
USING INDEX
;

ALTER TABLE TV_CLIENTES_TBL
ADD CONSTRAINT TV_CLIENTES_UK UNIQUE (CODALM, USUARIO)
USING INDEX
;

